package ats.blockchain.web.bean;

import java.math.BigDecimal;

import ats.blockchain.web.model.Basketinfo;
public class PackageInfo {
	private String aoc;
	private String basketno;
	private String productcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.SupplierCode
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String suppliercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.Suppliername
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String suppliername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.diamondsnumber
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private int diamondsnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.totalweight
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private BigDecimal totalweight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.mimweight
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private BigDecimal mimweight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.giacontrolno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String giacontrolno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.gradlab
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String gradlab;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.locgradlab
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String locgradlab;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.collectionadd
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String collectionadd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.invtymgr
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String invtymgr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.sealedbagno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String sealedbagno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.depaccno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String depaccno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.reverification
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String reverification;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.ownmgr
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String ownmgr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.auditor
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String auditor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.vault
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String vault;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.owner
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String owner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.location
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String location;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.auditdate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String auditdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.ownerdate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String ownerdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.locdate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String locdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.giaapproveddate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String giaapproveddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.result
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String result;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.status
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String status;
	public String getAoc() {
		return aoc;
	}
	public void setAoc(String aoc) {
		this.aoc = aoc;
	}
	public String getBasketno() {
		return basketno;
	}
	public void setBasketno(String basketno) {
		this.basketno = basketno;
	}
	public String getProductcode() {
		return productcode;
	}
	public void setProductcode(String productcode) {
		this.productcode = productcode;
	}
	public String getSuppliercode() {
		return suppliercode;
	}
	public void setSuppliercode(String suppliercode) {
		this.suppliercode = suppliercode;
	}
	public String getSuppliername() {
		return suppliername;
	}
	public void setSuppliername(String suppliername) {
		this.suppliername = suppliername;
	}
	public int getDiamondsnumber() {
		return diamondsnumber;
	}
	public void setDiamondsnumber(int diamondsnumber) {
		this.diamondsnumber = diamondsnumber;
	}
	public BigDecimal getTotalweight() {
		return totalweight;
	}
	public void setTotalweight(BigDecimal totalweight) {
		this.totalweight = totalweight;
	}
	public BigDecimal getMimweight() {
		return mimweight;
	}
	public void setMimweight(BigDecimal mimweight) {
		this.mimweight = mimweight;
	}
	public String getGiacontrolno() {
		return giacontrolno;
	}
	public void setGiacontrolno(String giacontrolno) {
		this.giacontrolno = giacontrolno;
	}
	public String getGradlab() {
		return gradlab;
	}
	public void setGradlab(String gradlab) {
		this.gradlab = gradlab;
	}

	public String getLocgradlab() {
		return locgradlab;
	}
	public void setLocgradlab(String locgradlab) {
		this.locgradlab = locgradlab;
	}
	public String getCollectionadd() {
		return collectionadd;
	}
	public void setCollectionadd(String collectionadd) {
		this.collectionadd = collectionadd;
	}
	public String getInvtymgr() {
		return invtymgr;
	}
	public void setInvtymgr(String invtymgr) {
		this.invtymgr = invtymgr;
	}
	public String getSealedbagno() {
		return sealedbagno;
	}
	public void setSealedbagno(String sealedbagno) {
		this.sealedbagno = sealedbagno;
	}
	public String getDepaccno() {
		return depaccno;
	}
	public void setDepaccno(String depaccno) {
		this.depaccno = depaccno;
	}

	public String getOwnmgr() {
		return ownmgr;
	}
	public void setOwnmgr(String ownmgr) {
		this.ownmgr = ownmgr;
	}
	public String getAuditor() {
		return auditor;
	}
	public void setAuditor(String auditor) {
		this.auditor = auditor;
	}
	public String getVault() {
		return vault;
	}
	public void setVault(String vault) {
		this.vault = vault;
	}
	public String getOwner() {
		return owner;
	}
	public void setOwner(String owner) {
		this.owner = owner;
	}
	public String getLocation() {
		return location;
	}
	public void setLocation(String location) {
		this.location = location;
	}
	public String getAuditdate() {
		return auditdate;
	}
	public void setAuditdate(String auditdate) {
		this.auditdate = auditdate;
	}
	public String getOwnerdate() {
		return ownerdate;
	}
	public void setOwnerdate(String ownerdate) {
		this.ownerdate = ownerdate;
	}
	public String getLocdate() {
		return locdate;
	}
	public void setLocdate(String locdate) {
		this.locdate = locdate;
	}
	public String getGiaapproveddate() {
		return giaapproveddate;
	}
	public void setGiaapproveddate(String giaapproveddate) {
		this.giaapproveddate = giaapproveddate;
	}
	public String getResult() {
		return result;
	}
	public void setResult(String result) {
		this.result = result;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Basketinfo [aoc=");
		builder.append(aoc);
		builder.append(", basketno=");
		builder.append(basketno);
		builder.append(", productcode=");
		builder.append(productcode);
		builder.append(", suppliercode=");
		builder.append(suppliercode);
		builder.append(", suppliername=");
		builder.append(suppliername);
		builder.append(", diamondsnumber=");
		builder.append(diamondsnumber);
		builder.append(", totalweight=");
		builder.append(totalweight);
		builder.append(", mimweight=");
		builder.append(mimweight);
		builder.append(", giacontrolno=");
		builder.append(giacontrolno);
		builder.append(", gradlab=");
		builder.append(gradlab);
		builder.append(", gradLabLocation=");
		builder.append(locgradlab);
		builder.append(", collectionadr=");
		builder.append(collectionadd);
		builder.append(", invtymgr=");
		builder.append(invtymgr);
		builder.append(", sealedbagno=");
		builder.append(sealedbagno);
		builder.append(", depaccno=");
		builder.append(depaccno);
		builder.append(", reVerificationId=");
		builder.append(reverification);
		builder.append(", ownmgr=");
		builder.append(ownmgr);
		builder.append(", auditor=");
		builder.append(auditor);
		builder.append(", vault=");
		builder.append(vault);
		builder.append(", owner=");
		builder.append(owner);
		builder.append(", location=");
		builder.append(location);
		builder.append(", auditdate=");
		builder.append(auditdate);
		builder.append(", ownerdate=");
		builder.append(ownerdate);
		builder.append(", locdate=");
		builder.append(locdate);
		builder.append(", giaapproveddate=");
		builder.append(giaapproveddate);
		builder.append(", result=");
		builder.append(result);
		builder.append(", status=");
		builder.append(status);
		builder.append("]");
		return builder.toString();
	}
	
}