package ats.blockchain.web.model;

import java.math.BigDecimal;
public class Basketinfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.basketno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String basketno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.productcode
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String productcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.SupplierCode
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String suppliercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.Suppliername
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String suppliername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.diamondsnumber
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private Long diamondsnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.totalweight
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private BigDecimal totalweight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.mimweight
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private BigDecimal mimweight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.giacontrolno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String giacontrolno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.gradlab
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String gradlab;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.locgradlab
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String locgradlab;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.collectionadd
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String collectionadd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.invtymgr
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String invtymgr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.sealedbagno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String sealedbagno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.depaccno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String depaccno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.reverification
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String reverification;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.ownmgr
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String ownmgr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.auditor
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String auditor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.vault
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String vault;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.owner
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String owner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.location
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String location;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.auditdate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String auditdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.ownerdate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String ownerdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.locdate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String locdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.giaapproveddate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String giaapproveddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.result
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String result;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basketinfo.status
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.basketno
	 * @return  the value of basketinfo.basketno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getBasketno()
	{
		return basketno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.basketno
	 * @param basketno  the value for basketinfo.basketno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setBasketno(String basketno)
	{
		this.basketno = basketno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.productcode
	 * @return  the value of basketinfo.productcode
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getProductcode()
	{
		return productcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.productcode
	 * @param productcode  the value for basketinfo.productcode
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setProductcode(String productcode)
	{
		this.productcode = productcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.SupplierCode
	 * @return  the value of basketinfo.SupplierCode
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getSuppliercode()
	{
		return suppliercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.SupplierCode
	 * @param suppliercode  the value for basketinfo.SupplierCode
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setSuppliercode(String suppliercode)
	{
		this.suppliercode = suppliercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.Suppliername
	 * @return  the value of basketinfo.Suppliername
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getSuppliername()
	{
		return suppliername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.Suppliername
	 * @param suppliername  the value for basketinfo.Suppliername
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setSuppliername(String suppliername)
	{
		this.suppliername = suppliername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.diamondsnumber
	 * @return  the value of basketinfo.diamondsnumber
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public Long getDiamondsnumber()
	{
		return diamondsnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.diamondsnumber
	 * @param diamondsnumber  the value for basketinfo.diamondsnumber
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setDiamondsnumber(Long diamondsnumber)
	{
		this.diamondsnumber = diamondsnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.totalweight
	 * @return  the value of basketinfo.totalweight
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public BigDecimal getTotalweight()
	{
		return totalweight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.totalweight
	 * @param totalweight  the value for basketinfo.totalweight
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setTotalweight(BigDecimal totalweight)
	{
		this.totalweight = totalweight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.mimweight
	 * @return  the value of basketinfo.mimweight
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public BigDecimal getMimweight()
	{
		return mimweight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.mimweight
	 * @param mimweight  the value for basketinfo.mimweight
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setMimweight(BigDecimal mimweight)
	{
		this.mimweight = mimweight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.giacontrolno
	 * @return  the value of basketinfo.giacontrolno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getGiacontrolno()
	{
		return giacontrolno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.giacontrolno
	 * @param giacontrolno  the value for basketinfo.giacontrolno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setGiacontrolno(String giacontrolno)
	{
		this.giacontrolno = giacontrolno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.gradlab
	 * @return  the value of basketinfo.gradlab
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getGradlab()
	{
		return gradlab;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.gradlab
	 * @param gradlab  the value for basketinfo.gradlab
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setGradlab(String gradlab)
	{
		this.gradlab = gradlab;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.locgradlab
	 * @return  the value of basketinfo.locgradlab
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getLocgradlab()
	{
		return locgradlab;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.locgradlab
	 * @param locgradlab  the value for basketinfo.locgradlab
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setLocgradlab(String locgradlab)
	{
		this.locgradlab = locgradlab;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.collectionadd
	 * @return  the value of basketinfo.collectionadd
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getCollectionadd()
	{
		return collectionadd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.collectionadd
	 * @param collectionadd  the value for basketinfo.collectionadd
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setCollectionadd(String collectionadd)
	{
		this.collectionadd = collectionadd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.invtymgr
	 * @return  the value of basketinfo.invtymgr
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getInvtymgr()
	{
		return invtymgr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.invtymgr
	 * @param invtymgr  the value for basketinfo.invtymgr
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setInvtymgr(String invtymgr)
	{
		this.invtymgr = invtymgr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.sealedbagno
	 * @return  the value of basketinfo.sealedbagno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getSealedbagno()
	{
		return sealedbagno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.sealedbagno
	 * @param sealedbagno  the value for basketinfo.sealedbagno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setSealedbagno(String sealedbagno)
	{
		this.sealedbagno = sealedbagno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.depaccno
	 * @return  the value of basketinfo.depaccno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getDepaccno()
	{
		return depaccno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.depaccno
	 * @param depaccno  the value for basketinfo.depaccno
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setDepaccno(String depaccno)
	{
		this.depaccno = depaccno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.reverification
	 * @return  the value of basketinfo.reverification
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getReverification()
	{
		return reverification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.reverification
	 * @param reverification  the value for basketinfo.reverification
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setReverification(String reverification)
	{
		this.reverification = reverification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.ownmgr
	 * @return  the value of basketinfo.ownmgr
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getOwnmgr()
	{
		return ownmgr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.ownmgr
	 * @param ownmgr  the value for basketinfo.ownmgr
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setOwnmgr(String ownmgr)
	{
		this.ownmgr = ownmgr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.auditor
	 * @return  the value of basketinfo.auditor
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getAuditor()
	{
		return auditor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.auditor
	 * @param auditor  the value for basketinfo.auditor
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setAuditor(String auditor)
	{
		this.auditor = auditor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.vault
	 * @return  the value of basketinfo.vault
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getVault()
	{
		return vault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.vault
	 * @param vault  the value for basketinfo.vault
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setVault(String vault)
	{
		this.vault = vault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.owner
	 * @return  the value of basketinfo.owner
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getOwner()
	{
		return owner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.owner
	 * @param owner  the value for basketinfo.owner
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setOwner(String owner)
	{
		this.owner = owner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.location
	 * @return  the value of basketinfo.location
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getLocation()
	{
		return location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.location
	 * @param location  the value for basketinfo.location
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setLocation(String location)
	{
		this.location = location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.auditdate
	 * @return  the value of basketinfo.auditdate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getAuditdate()
	{
		return auditdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.auditdate
	 * @param auditdate  the value for basketinfo.auditdate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setAuditdate(String auditdate)
	{
		this.auditdate = auditdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.ownerdate
	 * @return  the value of basketinfo.ownerdate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getOwnerdate()
	{
		return ownerdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.ownerdate
	 * @param ownerdate  the value for basketinfo.ownerdate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setOwnerdate(String ownerdate)
	{
		this.ownerdate = ownerdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.locdate
	 * @return  the value of basketinfo.locdate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getLocdate()
	{
		return locdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.locdate
	 * @param locdate  the value for basketinfo.locdate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setLocdate(String locdate)
	{
		this.locdate = locdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.giaapproveddate
	 * @return  the value of basketinfo.giaapproveddate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getGiaapproveddate()
	{
		return giaapproveddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.giaapproveddate
	 * @param giaapproveddate  the value for basketinfo.giaapproveddate
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setGiaapproveddate(String giaapproveddate)
	{
		this.giaapproveddate = giaapproveddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.result
	 * @return  the value of basketinfo.result
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getResult()
	{
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.result
	 * @param result  the value for basketinfo.result
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setResult(String result)
	{
		this.result = result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basketinfo.status
	 * @return  the value of basketinfo.status
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getStatus()
	{
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basketinfo.status
	 * @param status  the value for basketinfo.status
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setStatus(String status)
	{
		this.status = status;
	}
}