package ats.blockchain.web.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class BasketinfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public BasketinfoExample()
	{
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setOrderByClause(String orderByClause)
	{
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public String getOrderByClause()
	{
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void setDistinct(boolean distinct)
	{
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public boolean isDistinct()
	{
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public List<Criteria> getOredCriteria()
	{
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void or(Criteria criteria)
	{
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public Criteria or()
	{
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public Criteria createCriteria()
	{
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0)
		{
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	protected Criteria createCriteriaInternal()
	{
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public void clear()
	{
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	protected abstract static class GeneratedCriteria
	{
		protected List<Criterion> criteria;

		protected GeneratedCriteria()
		{
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid()
		{
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria()
		{
			return criteria;
		}

		public List<Criterion> getCriteria()
		{
			return criteria;
		}

		protected void addCriterion(String condition)
		{
			if (condition == null)
			{
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property)
		{
			if (value == null)
			{
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property)
		{
			if (value1 == null || value2 == null)
			{
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBasketnoIsNull()
		{
			addCriterion("basketno is null");
			return (Criteria) this;
		}

		public Criteria andBasketnoIsNotNull()
		{
			addCriterion("basketno is not null");
			return (Criteria) this;
		}

		public Criteria andBasketnoEqualTo(String value)
		{
			addCriterion("basketno =", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoNotEqualTo(String value)
		{
			addCriterion("basketno <>", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoGreaterThan(String value)
		{
			addCriterion("basketno >", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoGreaterThanOrEqualTo(String value)
		{
			addCriterion("basketno >=", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoLessThan(String value)
		{
			addCriterion("basketno <", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoLessThanOrEqualTo(String value)
		{
			addCriterion("basketno <=", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoLike(String value)
		{
			addCriterion("basketno like", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoNotLike(String value)
		{
			addCriterion("basketno not like", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoIn(List<String> values)
		{
			addCriterion("basketno in", values, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoNotIn(List<String> values)
		{
			addCriterion("basketno not in", values, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoBetween(String value1, String value2)
		{
			addCriterion("basketno between", value1, value2, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoNotBetween(String value1, String value2)
		{
			addCriterion("basketno not between", value1, value2, "basketno");
			return (Criteria) this;
		}

		public Criteria andProductcodeIsNull()
		{
			addCriterion("productcode is null");
			return (Criteria) this;
		}

		public Criteria andProductcodeIsNotNull()
		{
			addCriterion("productcode is not null");
			return (Criteria) this;
		}

		public Criteria andProductcodeEqualTo(String value)
		{
			addCriterion("productcode =", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeNotEqualTo(String value)
		{
			addCriterion("productcode <>", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeGreaterThan(String value)
		{
			addCriterion("productcode >", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeGreaterThanOrEqualTo(String value)
		{
			addCriterion("productcode >=", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeLessThan(String value)
		{
			addCriterion("productcode <", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeLessThanOrEqualTo(String value)
		{
			addCriterion("productcode <=", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeLike(String value)
		{
			addCriterion("productcode like", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeNotLike(String value)
		{
			addCriterion("productcode not like", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeIn(List<String> values)
		{
			addCriterion("productcode in", values, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeNotIn(List<String> values)
		{
			addCriterion("productcode not in", values, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeBetween(String value1, String value2)
		{
			addCriterion("productcode between", value1, value2, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeNotBetween(String value1, String value2)
		{
			addCriterion("productcode not between", value1, value2, "productcode");
			return (Criteria) this;
		}

		public Criteria andSuppliercodeIsNull()
		{
			addCriterion("SupplierCode is null");
			return (Criteria) this;
		}

		public Criteria andSuppliercodeIsNotNull()
		{
			addCriterion("SupplierCode is not null");
			return (Criteria) this;
		}

		public Criteria andSuppliercodeEqualTo(String value)
		{
			addCriterion("SupplierCode =", value, "suppliercode");
			return (Criteria) this;
		}

		public Criteria andSuppliercodeNotEqualTo(String value)
		{
			addCriterion("SupplierCode <>", value, "suppliercode");
			return (Criteria) this;
		}

		public Criteria andSuppliercodeGreaterThan(String value)
		{
			addCriterion("SupplierCode >", value, "suppliercode");
			return (Criteria) this;
		}

		public Criteria andSuppliercodeGreaterThanOrEqualTo(String value)
		{
			addCriterion("SupplierCode >=", value, "suppliercode");
			return (Criteria) this;
		}

		public Criteria andSuppliercodeLessThan(String value)
		{
			addCriterion("SupplierCode <", value, "suppliercode");
			return (Criteria) this;
		}

		public Criteria andSuppliercodeLessThanOrEqualTo(String value)
		{
			addCriterion("SupplierCode <=", value, "suppliercode");
			return (Criteria) this;
		}

		public Criteria andSuppliercodeLike(String value)
		{
			addCriterion("SupplierCode like", value, "suppliercode");
			return (Criteria) this;
		}

		public Criteria andSuppliercodeNotLike(String value)
		{
			addCriterion("SupplierCode not like", value, "suppliercode");
			return (Criteria) this;
		}

		public Criteria andSuppliercodeIn(List<String> values)
		{
			addCriterion("SupplierCode in", values, "suppliercode");
			return (Criteria) this;
		}

		public Criteria andSuppliercodeNotIn(List<String> values)
		{
			addCriterion("SupplierCode not in", values, "suppliercode");
			return (Criteria) this;
		}

		public Criteria andSuppliercodeBetween(String value1, String value2)
		{
			addCriterion("SupplierCode between", value1, value2, "suppliercode");
			return (Criteria) this;
		}

		public Criteria andSuppliercodeNotBetween(String value1, String value2)
		{
			addCriterion("SupplierCode not between", value1, value2, "suppliercode");
			return (Criteria) this;
		}

		public Criteria andSuppliernameIsNull()
		{
			addCriterion("Suppliername is null");
			return (Criteria) this;
		}

		public Criteria andSuppliernameIsNotNull()
		{
			addCriterion("Suppliername is not null");
			return (Criteria) this;
		}

		public Criteria andSuppliernameEqualTo(String value)
		{
			addCriterion("Suppliername =", value, "suppliername");
			return (Criteria) this;
		}

		public Criteria andSuppliernameNotEqualTo(String value)
		{
			addCriterion("Suppliername <>", value, "suppliername");
			return (Criteria) this;
		}

		public Criteria andSuppliernameGreaterThan(String value)
		{
			addCriterion("Suppliername >", value, "suppliername");
			return (Criteria) this;
		}

		public Criteria andSuppliernameGreaterThanOrEqualTo(String value)
		{
			addCriterion("Suppliername >=", value, "suppliername");
			return (Criteria) this;
		}

		public Criteria andSuppliernameLessThan(String value)
		{
			addCriterion("Suppliername <", value, "suppliername");
			return (Criteria) this;
		}

		public Criteria andSuppliernameLessThanOrEqualTo(String value)
		{
			addCriterion("Suppliername <=", value, "suppliername");
			return (Criteria) this;
		}

		public Criteria andSuppliernameLike(String value)
		{
			addCriterion("Suppliername like", value, "suppliername");
			return (Criteria) this;
		}

		public Criteria andSuppliernameNotLike(String value)
		{
			addCriterion("Suppliername not like", value, "suppliername");
			return (Criteria) this;
		}

		public Criteria andSuppliernameIn(List<String> values)
		{
			addCriterion("Suppliername in", values, "suppliername");
			return (Criteria) this;
		}

		public Criteria andSuppliernameNotIn(List<String> values)
		{
			addCriterion("Suppliername not in", values, "suppliername");
			return (Criteria) this;
		}

		public Criteria andSuppliernameBetween(String value1, String value2)
		{
			addCriterion("Suppliername between", value1, value2, "suppliername");
			return (Criteria) this;
		}

		public Criteria andSuppliernameNotBetween(String value1, String value2)
		{
			addCriterion("Suppliername not between", value1, value2, "suppliername");
			return (Criteria) this;
		}

		public Criteria andDiamondsnumberIsNull()
		{
			addCriterion("diamondsnumber is null");
			return (Criteria) this;
		}

		public Criteria andDiamondsnumberIsNotNull()
		{
			addCriterion("diamondsnumber is not null");
			return (Criteria) this;
		}

		public Criteria andDiamondsnumberEqualTo(Long value)
		{
			addCriterion("diamondsnumber =", value, "diamondsnumber");
			return (Criteria) this;
		}

		public Criteria andDiamondsnumberNotEqualTo(Long value)
		{
			addCriterion("diamondsnumber <>", value, "diamondsnumber");
			return (Criteria) this;
		}

		public Criteria andDiamondsnumberGreaterThan(Long value)
		{
			addCriterion("diamondsnumber >", value, "diamondsnumber");
			return (Criteria) this;
		}

		public Criteria andDiamondsnumberGreaterThanOrEqualTo(Long value)
		{
			addCriterion("diamondsnumber >=", value, "diamondsnumber");
			return (Criteria) this;
		}

		public Criteria andDiamondsnumberLessThan(Long value)
		{
			addCriterion("diamondsnumber <", value, "diamondsnumber");
			return (Criteria) this;
		}

		public Criteria andDiamondsnumberLessThanOrEqualTo(Long value)
		{
			addCriterion("diamondsnumber <=", value, "diamondsnumber");
			return (Criteria) this;
		}

		public Criteria andDiamondsnumberIn(List<Long> values)
		{
			addCriterion("diamondsnumber in", values, "diamondsnumber");
			return (Criteria) this;
		}

		public Criteria andDiamondsnumberNotIn(List<Long> values)
		{
			addCriterion("diamondsnumber not in", values, "diamondsnumber");
			return (Criteria) this;
		}

		public Criteria andDiamondsnumberBetween(Long value1, Long value2)
		{
			addCriterion("diamondsnumber between", value1, value2, "diamondsnumber");
			return (Criteria) this;
		}

		public Criteria andDiamondsnumberNotBetween(Long value1, Long value2)
		{
			addCriterion("diamondsnumber not between", value1, value2, "diamondsnumber");
			return (Criteria) this;
		}

		public Criteria andTotalweightIsNull()
		{
			addCriterion("totalweight is null");
			return (Criteria) this;
		}

		public Criteria andTotalweightIsNotNull()
		{
			addCriterion("totalweight is not null");
			return (Criteria) this;
		}

		public Criteria andTotalweightEqualTo(BigDecimal value)
		{
			addCriterion("totalweight =", value, "totalweight");
			return (Criteria) this;
		}

		public Criteria andTotalweightNotEqualTo(BigDecimal value)
		{
			addCriterion("totalweight <>", value, "totalweight");
			return (Criteria) this;
		}

		public Criteria andTotalweightGreaterThan(BigDecimal value)
		{
			addCriterion("totalweight >", value, "totalweight");
			return (Criteria) this;
		}

		public Criteria andTotalweightGreaterThanOrEqualTo(BigDecimal value)
		{
			addCriterion("totalweight >=", value, "totalweight");
			return (Criteria) this;
		}

		public Criteria andTotalweightLessThan(BigDecimal value)
		{
			addCriterion("totalweight <", value, "totalweight");
			return (Criteria) this;
		}

		public Criteria andTotalweightLessThanOrEqualTo(BigDecimal value)
		{
			addCriterion("totalweight <=", value, "totalweight");
			return (Criteria) this;
		}

		public Criteria andTotalweightIn(List<BigDecimal> values)
		{
			addCriterion("totalweight in", values, "totalweight");
			return (Criteria) this;
		}

		public Criteria andTotalweightNotIn(List<BigDecimal> values)
		{
			addCriterion("totalweight not in", values, "totalweight");
			return (Criteria) this;
		}

		public Criteria andTotalweightBetween(BigDecimal value1, BigDecimal value2)
		{
			addCriterion("totalweight between", value1, value2, "totalweight");
			return (Criteria) this;
		}

		public Criteria andTotalweightNotBetween(BigDecimal value1, BigDecimal value2)
		{
			addCriterion("totalweight not between", value1, value2, "totalweight");
			return (Criteria) this;
		}

		public Criteria andMimweightIsNull()
		{
			addCriterion("mimweight is null");
			return (Criteria) this;
		}

		public Criteria andMimweightIsNotNull()
		{
			addCriterion("mimweight is not null");
			return (Criteria) this;
		}

		public Criteria andMimweightEqualTo(BigDecimal value)
		{
			addCriterion("mimweight =", value, "mimweight");
			return (Criteria) this;
		}

		public Criteria andMimweightNotEqualTo(BigDecimal value)
		{
			addCriterion("mimweight <>", value, "mimweight");
			return (Criteria) this;
		}

		public Criteria andMimweightGreaterThan(BigDecimal value)
		{
			addCriterion("mimweight >", value, "mimweight");
			return (Criteria) this;
		}

		public Criteria andMimweightGreaterThanOrEqualTo(BigDecimal value)
		{
			addCriterion("mimweight >=", value, "mimweight");
			return (Criteria) this;
		}

		public Criteria andMimweightLessThan(BigDecimal value)
		{
			addCriterion("mimweight <", value, "mimweight");
			return (Criteria) this;
		}

		public Criteria andMimweightLessThanOrEqualTo(BigDecimal value)
		{
			addCriterion("mimweight <=", value, "mimweight");
			return (Criteria) this;
		}

		public Criteria andMimweightIn(List<BigDecimal> values)
		{
			addCriterion("mimweight in", values, "mimweight");
			return (Criteria) this;
		}

		public Criteria andMimweightNotIn(List<BigDecimal> values)
		{
			addCriterion("mimweight not in", values, "mimweight");
			return (Criteria) this;
		}

		public Criteria andMimweightBetween(BigDecimal value1, BigDecimal value2)
		{
			addCriterion("mimweight between", value1, value2, "mimweight");
			return (Criteria) this;
		}

		public Criteria andMimweightNotBetween(BigDecimal value1, BigDecimal value2)
		{
			addCriterion("mimweight not between", value1, value2, "mimweight");
			return (Criteria) this;
		}

		public Criteria andGiacontrolnoIsNull()
		{
			addCriterion("giacontrolno is null");
			return (Criteria) this;
		}

		public Criteria andGiacontrolnoIsNotNull()
		{
			addCriterion("giacontrolno is not null");
			return (Criteria) this;
		}

		public Criteria andGiacontrolnoEqualTo(String value)
		{
			addCriterion("giacontrolno =", value, "giacontrolno");
			return (Criteria) this;
		}

		public Criteria andGiacontrolnoNotEqualTo(String value)
		{
			addCriterion("giacontrolno <>", value, "giacontrolno");
			return (Criteria) this;
		}

		public Criteria andGiacontrolnoGreaterThan(String value)
		{
			addCriterion("giacontrolno >", value, "giacontrolno");
			return (Criteria) this;
		}

		public Criteria andGiacontrolnoGreaterThanOrEqualTo(String value)
		{
			addCriterion("giacontrolno >=", value, "giacontrolno");
			return (Criteria) this;
		}

		public Criteria andGiacontrolnoLessThan(String value)
		{
			addCriterion("giacontrolno <", value, "giacontrolno");
			return (Criteria) this;
		}

		public Criteria andGiacontrolnoLessThanOrEqualTo(String value)
		{
			addCriterion("giacontrolno <=", value, "giacontrolno");
			return (Criteria) this;
		}

		public Criteria andGiacontrolnoLike(String value)
		{
			addCriterion("giacontrolno like", value, "giacontrolno");
			return (Criteria) this;
		}

		public Criteria andGiacontrolnoNotLike(String value)
		{
			addCriterion("giacontrolno not like", value, "giacontrolno");
			return (Criteria) this;
		}

		public Criteria andGiacontrolnoIn(List<String> values)
		{
			addCriterion("giacontrolno in", values, "giacontrolno");
			return (Criteria) this;
		}

		public Criteria andGiacontrolnoNotIn(List<String> values)
		{
			addCriterion("giacontrolno not in", values, "giacontrolno");
			return (Criteria) this;
		}

		public Criteria andGiacontrolnoBetween(String value1, String value2)
		{
			addCriterion("giacontrolno between", value1, value2, "giacontrolno");
			return (Criteria) this;
		}

		public Criteria andGiacontrolnoNotBetween(String value1, String value2)
		{
			addCriterion("giacontrolno not between", value1, value2, "giacontrolno");
			return (Criteria) this;
		}

		public Criteria andGradlabIsNull()
		{
			addCriterion("gradlab is null");
			return (Criteria) this;
		}

		public Criteria andGradlabIsNotNull()
		{
			addCriterion("gradlab is not null");
			return (Criteria) this;
		}

		public Criteria andGradlabEqualTo(String value)
		{
			addCriterion("gradlab =", value, "gradlab");
			return (Criteria) this;
		}

		public Criteria andGradlabNotEqualTo(String value)
		{
			addCriterion("gradlab <>", value, "gradlab");
			return (Criteria) this;
		}

		public Criteria andGradlabGreaterThan(String value)
		{
			addCriterion("gradlab >", value, "gradlab");
			return (Criteria) this;
		}

		public Criteria andGradlabGreaterThanOrEqualTo(String value)
		{
			addCriterion("gradlab >=", value, "gradlab");
			return (Criteria) this;
		}

		public Criteria andGradlabLessThan(String value)
		{
			addCriterion("gradlab <", value, "gradlab");
			return (Criteria) this;
		}

		public Criteria andGradlabLessThanOrEqualTo(String value)
		{
			addCriterion("gradlab <=", value, "gradlab");
			return (Criteria) this;
		}

		public Criteria andGradlabLike(String value)
		{
			addCriterion("gradlab like", value, "gradlab");
			return (Criteria) this;
		}

		public Criteria andGradlabNotLike(String value)
		{
			addCriterion("gradlab not like", value, "gradlab");
			return (Criteria) this;
		}

		public Criteria andGradlabIn(List<String> values)
		{
			addCriterion("gradlab in", values, "gradlab");
			return (Criteria) this;
		}

		public Criteria andGradlabNotIn(List<String> values)
		{
			addCriterion("gradlab not in", values, "gradlab");
			return (Criteria) this;
		}

		public Criteria andGradlabBetween(String value1, String value2)
		{
			addCriterion("gradlab between", value1, value2, "gradlab");
			return (Criteria) this;
		}

		public Criteria andGradlabNotBetween(String value1, String value2)
		{
			addCriterion("gradlab not between", value1, value2, "gradlab");
			return (Criteria) this;
		}

		public Criteria andLocgradlabIsNull()
		{
			addCriterion("locgradlab is null");
			return (Criteria) this;
		}

		public Criteria andLocgradlabIsNotNull()
		{
			addCriterion("locgradlab is not null");
			return (Criteria) this;
		}

		public Criteria andLocgradlabEqualTo(String value)
		{
			addCriterion("locgradlab =", value, "locgradlab");
			return (Criteria) this;
		}

		public Criteria andLocgradlabNotEqualTo(String value)
		{
			addCriterion("locgradlab <>", value, "locgradlab");
			return (Criteria) this;
		}

		public Criteria andLocgradlabGreaterThan(String value)
		{
			addCriterion("locgradlab >", value, "locgradlab");
			return (Criteria) this;
		}

		public Criteria andLocgradlabGreaterThanOrEqualTo(String value)
		{
			addCriterion("locgradlab >=", value, "locgradlab");
			return (Criteria) this;
		}

		public Criteria andLocgradlabLessThan(String value)
		{
			addCriterion("locgradlab <", value, "locgradlab");
			return (Criteria) this;
		}

		public Criteria andLocgradlabLessThanOrEqualTo(String value)
		{
			addCriterion("locgradlab <=", value, "locgradlab");
			return (Criteria) this;
		}

		public Criteria andLocgradlabLike(String value)
		{
			addCriterion("locgradlab like", value, "locgradlab");
			return (Criteria) this;
		}

		public Criteria andLocgradlabNotLike(String value)
		{
			addCriterion("locgradlab not like", value, "locgradlab");
			return (Criteria) this;
		}

		public Criteria andLocgradlabIn(List<String> values)
		{
			addCriterion("locgradlab in", values, "locgradlab");
			return (Criteria) this;
		}

		public Criteria andLocgradlabNotIn(List<String> values)
		{
			addCriterion("locgradlab not in", values, "locgradlab");
			return (Criteria) this;
		}

		public Criteria andLocgradlabBetween(String value1, String value2)
		{
			addCriterion("locgradlab between", value1, value2, "locgradlab");
			return (Criteria) this;
		}

		public Criteria andLocgradlabNotBetween(String value1, String value2)
		{
			addCriterion("locgradlab not between", value1, value2, "locgradlab");
			return (Criteria) this;
		}

		public Criteria andCollectionaddIsNull()
		{
			addCriterion("collectionadd is null");
			return (Criteria) this;
		}

		public Criteria andCollectionaddIsNotNull()
		{
			addCriterion("collectionadd is not null");
			return (Criteria) this;
		}

		public Criteria andCollectionaddEqualTo(String value)
		{
			addCriterion("collectionadd =", value, "collectionadd");
			return (Criteria) this;
		}

		public Criteria andCollectionaddNotEqualTo(String value)
		{
			addCriterion("collectionadd <>", value, "collectionadd");
			return (Criteria) this;
		}

		public Criteria andCollectionaddGreaterThan(String value)
		{
			addCriterion("collectionadd >", value, "collectionadd");
			return (Criteria) this;
		}

		public Criteria andCollectionaddGreaterThanOrEqualTo(String value)
		{
			addCriterion("collectionadd >=", value, "collectionadd");
			return (Criteria) this;
		}

		public Criteria andCollectionaddLessThan(String value)
		{
			addCriterion("collectionadd <", value, "collectionadd");
			return (Criteria) this;
		}

		public Criteria andCollectionaddLessThanOrEqualTo(String value)
		{
			addCriterion("collectionadd <=", value, "collectionadd");
			return (Criteria) this;
		}

		public Criteria andCollectionaddLike(String value)
		{
			addCriterion("collectionadd like", value, "collectionadd");
			return (Criteria) this;
		}

		public Criteria andCollectionaddNotLike(String value)
		{
			addCriterion("collectionadd not like", value, "collectionadd");
			return (Criteria) this;
		}

		public Criteria andCollectionaddIn(List<String> values)
		{
			addCriterion("collectionadd in", values, "collectionadd");
			return (Criteria) this;
		}

		public Criteria andCollectionaddNotIn(List<String> values)
		{
			addCriterion("collectionadd not in", values, "collectionadd");
			return (Criteria) this;
		}

		public Criteria andCollectionaddBetween(String value1, String value2)
		{
			addCriterion("collectionadd between", value1, value2, "collectionadd");
			return (Criteria) this;
		}

		public Criteria andCollectionaddNotBetween(String value1, String value2)
		{
			addCriterion("collectionadd not between", value1, value2, "collectionadd");
			return (Criteria) this;
		}

		public Criteria andInvtymgrIsNull()
		{
			addCriterion("invtymgr is null");
			return (Criteria) this;
		}

		public Criteria andInvtymgrIsNotNull()
		{
			addCriterion("invtymgr is not null");
			return (Criteria) this;
		}

		public Criteria andInvtymgrEqualTo(String value)
		{
			addCriterion("invtymgr =", value, "invtymgr");
			return (Criteria) this;
		}

		public Criteria andInvtymgrNotEqualTo(String value)
		{
			addCriterion("invtymgr <>", value, "invtymgr");
			return (Criteria) this;
		}

		public Criteria andInvtymgrGreaterThan(String value)
		{
			addCriterion("invtymgr >", value, "invtymgr");
			return (Criteria) this;
		}

		public Criteria andInvtymgrGreaterThanOrEqualTo(String value)
		{
			addCriterion("invtymgr >=", value, "invtymgr");
			return (Criteria) this;
		}

		public Criteria andInvtymgrLessThan(String value)
		{
			addCriterion("invtymgr <", value, "invtymgr");
			return (Criteria) this;
		}

		public Criteria andInvtymgrLessThanOrEqualTo(String value)
		{
			addCriterion("invtymgr <=", value, "invtymgr");
			return (Criteria) this;
		}

		public Criteria andInvtymgrLike(String value)
		{
			addCriterion("invtymgr like", value, "invtymgr");
			return (Criteria) this;
		}

		public Criteria andInvtymgrNotLike(String value)
		{
			addCriterion("invtymgr not like", value, "invtymgr");
			return (Criteria) this;
		}

		public Criteria andInvtymgrIn(List<String> values)
		{
			addCriterion("invtymgr in", values, "invtymgr");
			return (Criteria) this;
		}

		public Criteria andInvtymgrNotIn(List<String> values)
		{
			addCriterion("invtymgr not in", values, "invtymgr");
			return (Criteria) this;
		}

		public Criteria andInvtymgrBetween(String value1, String value2)
		{
			addCriterion("invtymgr between", value1, value2, "invtymgr");
			return (Criteria) this;
		}

		public Criteria andInvtymgrNotBetween(String value1, String value2)
		{
			addCriterion("invtymgr not between", value1, value2, "invtymgr");
			return (Criteria) this;
		}

		public Criteria andSealedbagnoIsNull()
		{
			addCriterion("sealedbagno is null");
			return (Criteria) this;
		}

		public Criteria andSealedbagnoIsNotNull()
		{
			addCriterion("sealedbagno is not null");
			return (Criteria) this;
		}

		public Criteria andSealedbagnoEqualTo(String value)
		{
			addCriterion("sealedbagno =", value, "sealedbagno");
			return (Criteria) this;
		}

		public Criteria andSealedbagnoNotEqualTo(String value)
		{
			addCriterion("sealedbagno <>", value, "sealedbagno");
			return (Criteria) this;
		}

		public Criteria andSealedbagnoGreaterThan(String value)
		{
			addCriterion("sealedbagno >", value, "sealedbagno");
			return (Criteria) this;
		}

		public Criteria andSealedbagnoGreaterThanOrEqualTo(String value)
		{
			addCriterion("sealedbagno >=", value, "sealedbagno");
			return (Criteria) this;
		}

		public Criteria andSealedbagnoLessThan(String value)
		{
			addCriterion("sealedbagno <", value, "sealedbagno");
			return (Criteria) this;
		}

		public Criteria andSealedbagnoLessThanOrEqualTo(String value)
		{
			addCriterion("sealedbagno <=", value, "sealedbagno");
			return (Criteria) this;
		}

		public Criteria andSealedbagnoLike(String value)
		{
			addCriterion("sealedbagno like", value, "sealedbagno");
			return (Criteria) this;
		}

		public Criteria andSealedbagnoNotLike(String value)
		{
			addCriterion("sealedbagno not like", value, "sealedbagno");
			return (Criteria) this;
		}

		public Criteria andSealedbagnoIn(List<String> values)
		{
			addCriterion("sealedbagno in", values, "sealedbagno");
			return (Criteria) this;
		}

		public Criteria andSealedbagnoNotIn(List<String> values)
		{
			addCriterion("sealedbagno not in", values, "sealedbagno");
			return (Criteria) this;
		}

		public Criteria andSealedbagnoBetween(String value1, String value2)
		{
			addCriterion("sealedbagno between", value1, value2, "sealedbagno");
			return (Criteria) this;
		}

		public Criteria andSealedbagnoNotBetween(String value1, String value2)
		{
			addCriterion("sealedbagno not between", value1, value2, "sealedbagno");
			return (Criteria) this;
		}

		public Criteria andDepaccnoIsNull()
		{
			addCriterion("depaccno is null");
			return (Criteria) this;
		}

		public Criteria andDepaccnoIsNotNull()
		{
			addCriterion("depaccno is not null");
			return (Criteria) this;
		}

		public Criteria andDepaccnoEqualTo(String value)
		{
			addCriterion("depaccno =", value, "depaccno");
			return (Criteria) this;
		}

		public Criteria andDepaccnoNotEqualTo(String value)
		{
			addCriterion("depaccno <>", value, "depaccno");
			return (Criteria) this;
		}

		public Criteria andDepaccnoGreaterThan(String value)
		{
			addCriterion("depaccno >", value, "depaccno");
			return (Criteria) this;
		}

		public Criteria andDepaccnoGreaterThanOrEqualTo(String value)
		{
			addCriterion("depaccno >=", value, "depaccno");
			return (Criteria) this;
		}

		public Criteria andDepaccnoLessThan(String value)
		{
			addCriterion("depaccno <", value, "depaccno");
			return (Criteria) this;
		}

		public Criteria andDepaccnoLessThanOrEqualTo(String value)
		{
			addCriterion("depaccno <=", value, "depaccno");
			return (Criteria) this;
		}

		public Criteria andDepaccnoLike(String value)
		{
			addCriterion("depaccno like", value, "depaccno");
			return (Criteria) this;
		}

		public Criteria andDepaccnoNotLike(String value)
		{
			addCriterion("depaccno not like", value, "depaccno");
			return (Criteria) this;
		}

		public Criteria andDepaccnoIn(List<String> values)
		{
			addCriterion("depaccno in", values, "depaccno");
			return (Criteria) this;
		}

		public Criteria andDepaccnoNotIn(List<String> values)
		{
			addCriterion("depaccno not in", values, "depaccno");
			return (Criteria) this;
		}

		public Criteria andDepaccnoBetween(String value1, String value2)
		{
			addCriterion("depaccno between", value1, value2, "depaccno");
			return (Criteria) this;
		}

		public Criteria andDepaccnoNotBetween(String value1, String value2)
		{
			addCriterion("depaccno not between", value1, value2, "depaccno");
			return (Criteria) this;
		}

		public Criteria andReverificationIsNull()
		{
			addCriterion("reverification is null");
			return (Criteria) this;
		}

		public Criteria andReverificationIsNotNull()
		{
			addCriterion("reverification is not null");
			return (Criteria) this;
		}

		public Criteria andReverificationEqualTo(String value)
		{
			addCriterion("reverification =", value, "reverification");
			return (Criteria) this;
		}

		public Criteria andReverificationNotEqualTo(String value)
		{
			addCriterion("reverification <>", value, "reverification");
			return (Criteria) this;
		}

		public Criteria andReverificationGreaterThan(String value)
		{
			addCriterion("reverification >", value, "reverification");
			return (Criteria) this;
		}

		public Criteria andReverificationGreaterThanOrEqualTo(String value)
		{
			addCriterion("reverification >=", value, "reverification");
			return (Criteria) this;
		}

		public Criteria andReverificationLessThan(String value)
		{
			addCriterion("reverification <", value, "reverification");
			return (Criteria) this;
		}

		public Criteria andReverificationLessThanOrEqualTo(String value)
		{
			addCriterion("reverification <=", value, "reverification");
			return (Criteria) this;
		}

		public Criteria andReverificationLike(String value)
		{
			addCriterion("reverification like", value, "reverification");
			return (Criteria) this;
		}

		public Criteria andReverificationNotLike(String value)
		{
			addCriterion("reverification not like", value, "reverification");
			return (Criteria) this;
		}

		public Criteria andReverificationIn(List<String> values)
		{
			addCriterion("reverification in", values, "reverification");
			return (Criteria) this;
		}

		public Criteria andReverificationNotIn(List<String> values)
		{
			addCriterion("reverification not in", values, "reverification");
			return (Criteria) this;
		}

		public Criteria andReverificationBetween(String value1, String value2)
		{
			addCriterion("reverification between", value1, value2, "reverification");
			return (Criteria) this;
		}

		public Criteria andReverificationNotBetween(String value1, String value2)
		{
			addCriterion("reverification not between", value1, value2, "reverification");
			return (Criteria) this;
		}

		public Criteria andOwnmgrIsNull()
		{
			addCriterion("ownmgr is null");
			return (Criteria) this;
		}

		public Criteria andOwnmgrIsNotNull()
		{
			addCriterion("ownmgr is not null");
			return (Criteria) this;
		}

		public Criteria andOwnmgrEqualTo(String value)
		{
			addCriterion("ownmgr =", value, "ownmgr");
			return (Criteria) this;
		}

		public Criteria andOwnmgrNotEqualTo(String value)
		{
			addCriterion("ownmgr <>", value, "ownmgr");
			return (Criteria) this;
		}

		public Criteria andOwnmgrGreaterThan(String value)
		{
			addCriterion("ownmgr >", value, "ownmgr");
			return (Criteria) this;
		}

		public Criteria andOwnmgrGreaterThanOrEqualTo(String value)
		{
			addCriterion("ownmgr >=", value, "ownmgr");
			return (Criteria) this;
		}

		public Criteria andOwnmgrLessThan(String value)
		{
			addCriterion("ownmgr <", value, "ownmgr");
			return (Criteria) this;
		}

		public Criteria andOwnmgrLessThanOrEqualTo(String value)
		{
			addCriterion("ownmgr <=", value, "ownmgr");
			return (Criteria) this;
		}

		public Criteria andOwnmgrLike(String value)
		{
			addCriterion("ownmgr like", value, "ownmgr");
			return (Criteria) this;
		}

		public Criteria andOwnmgrNotLike(String value)
		{
			addCriterion("ownmgr not like", value, "ownmgr");
			return (Criteria) this;
		}

		public Criteria andOwnmgrIn(List<String> values)
		{
			addCriterion("ownmgr in", values, "ownmgr");
			return (Criteria) this;
		}

		public Criteria andOwnmgrNotIn(List<String> values)
		{
			addCriterion("ownmgr not in", values, "ownmgr");
			return (Criteria) this;
		}

		public Criteria andOwnmgrBetween(String value1, String value2)
		{
			addCriterion("ownmgr between", value1, value2, "ownmgr");
			return (Criteria) this;
		}

		public Criteria andOwnmgrNotBetween(String value1, String value2)
		{
			addCriterion("ownmgr not between", value1, value2, "ownmgr");
			return (Criteria) this;
		}

		public Criteria andAuditorIsNull()
		{
			addCriterion("auditor is null");
			return (Criteria) this;
		}

		public Criteria andAuditorIsNotNull()
		{
			addCriterion("auditor is not null");
			return (Criteria) this;
		}

		public Criteria andAuditorEqualTo(String value)
		{
			addCriterion("auditor =", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorNotEqualTo(String value)
		{
			addCriterion("auditor <>", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorGreaterThan(String value)
		{
			addCriterion("auditor >", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorGreaterThanOrEqualTo(String value)
		{
			addCriterion("auditor >=", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorLessThan(String value)
		{
			addCriterion("auditor <", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorLessThanOrEqualTo(String value)
		{
			addCriterion("auditor <=", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorLike(String value)
		{
			addCriterion("auditor like", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorNotLike(String value)
		{
			addCriterion("auditor not like", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorIn(List<String> values)
		{
			addCriterion("auditor in", values, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorNotIn(List<String> values)
		{
			addCriterion("auditor not in", values, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorBetween(String value1, String value2)
		{
			addCriterion("auditor between", value1, value2, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorNotBetween(String value1, String value2)
		{
			addCriterion("auditor not between", value1, value2, "auditor");
			return (Criteria) this;
		}

		public Criteria andVaultIsNull()
		{
			addCriterion("vault is null");
			return (Criteria) this;
		}

		public Criteria andVaultIsNotNull()
		{
			addCriterion("vault is not null");
			return (Criteria) this;
		}

		public Criteria andVaultEqualTo(String value)
		{
			addCriterion("vault =", value, "vault");
			return (Criteria) this;
		}

		public Criteria andVaultNotEqualTo(String value)
		{
			addCriterion("vault <>", value, "vault");
			return (Criteria) this;
		}

		public Criteria andVaultGreaterThan(String value)
		{
			addCriterion("vault >", value, "vault");
			return (Criteria) this;
		}

		public Criteria andVaultGreaterThanOrEqualTo(String value)
		{
			addCriterion("vault >=", value, "vault");
			return (Criteria) this;
		}

		public Criteria andVaultLessThan(String value)
		{
			addCriterion("vault <", value, "vault");
			return (Criteria) this;
		}

		public Criteria andVaultLessThanOrEqualTo(String value)
		{
			addCriterion("vault <=", value, "vault");
			return (Criteria) this;
		}

		public Criteria andVaultLike(String value)
		{
			addCriterion("vault like", value, "vault");
			return (Criteria) this;
		}

		public Criteria andVaultNotLike(String value)
		{
			addCriterion("vault not like", value, "vault");
			return (Criteria) this;
		}

		public Criteria andVaultIn(List<String> values)
		{
			addCriterion("vault in", values, "vault");
			return (Criteria) this;
		}

		public Criteria andVaultNotIn(List<String> values)
		{
			addCriterion("vault not in", values, "vault");
			return (Criteria) this;
		}

		public Criteria andVaultBetween(String value1, String value2)
		{
			addCriterion("vault between", value1, value2, "vault");
			return (Criteria) this;
		}

		public Criteria andVaultNotBetween(String value1, String value2)
		{
			addCriterion("vault not between", value1, value2, "vault");
			return (Criteria) this;
		}

		public Criteria andOwnerIsNull()
		{
			addCriterion("owner is null");
			return (Criteria) this;
		}

		public Criteria andOwnerIsNotNull()
		{
			addCriterion("owner is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerEqualTo(String value)
		{
			addCriterion("owner =", value, "owner");
			return (Criteria) this;
		}

		public Criteria andOwnerNotEqualTo(String value)
		{
			addCriterion("owner <>", value, "owner");
			return (Criteria) this;
		}

		public Criteria andOwnerGreaterThan(String value)
		{
			addCriterion("owner >", value, "owner");
			return (Criteria) this;
		}

		public Criteria andOwnerGreaterThanOrEqualTo(String value)
		{
			addCriterion("owner >=", value, "owner");
			return (Criteria) this;
		}

		public Criteria andOwnerLessThan(String value)
		{
			addCriterion("owner <", value, "owner");
			return (Criteria) this;
		}

		public Criteria andOwnerLessThanOrEqualTo(String value)
		{
			addCriterion("owner <=", value, "owner");
			return (Criteria) this;
		}

		public Criteria andOwnerLike(String value)
		{
			addCriterion("owner like", value, "owner");
			return (Criteria) this;
		}

		public Criteria andOwnerNotLike(String value)
		{
			addCriterion("owner not like", value, "owner");
			return (Criteria) this;
		}

		public Criteria andOwnerIn(List<String> values)
		{
			addCriterion("owner in", values, "owner");
			return (Criteria) this;
		}

		public Criteria andOwnerNotIn(List<String> values)
		{
			addCriterion("owner not in", values, "owner");
			return (Criteria) this;
		}

		public Criteria andOwnerBetween(String value1, String value2)
		{
			addCriterion("owner between", value1, value2, "owner");
			return (Criteria) this;
		}

		public Criteria andOwnerNotBetween(String value1, String value2)
		{
			addCriterion("owner not between", value1, value2, "owner");
			return (Criteria) this;
		}

		public Criteria andLocationIsNull()
		{
			addCriterion("location is null");
			return (Criteria) this;
		}

		public Criteria andLocationIsNotNull()
		{
			addCriterion("location is not null");
			return (Criteria) this;
		}

		public Criteria andLocationEqualTo(String value)
		{
			addCriterion("location =", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationNotEqualTo(String value)
		{
			addCriterion("location <>", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationGreaterThan(String value)
		{
			addCriterion("location >", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationGreaterThanOrEqualTo(String value)
		{
			addCriterion("location >=", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationLessThan(String value)
		{
			addCriterion("location <", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationLessThanOrEqualTo(String value)
		{
			addCriterion("location <=", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationLike(String value)
		{
			addCriterion("location like", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationNotLike(String value)
		{
			addCriterion("location not like", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationIn(List<String> values)
		{
			addCriterion("location in", values, "location");
			return (Criteria) this;
		}

		public Criteria andLocationNotIn(List<String> values)
		{
			addCriterion("location not in", values, "location");
			return (Criteria) this;
		}

		public Criteria andLocationBetween(String value1, String value2)
		{
			addCriterion("location between", value1, value2, "location");
			return (Criteria) this;
		}

		public Criteria andLocationNotBetween(String value1, String value2)
		{
			addCriterion("location not between", value1, value2, "location");
			return (Criteria) this;
		}

		public Criteria andAuditdateIsNull()
		{
			addCriterion("auditdate is null");
			return (Criteria) this;
		}

		public Criteria andAuditdateIsNotNull()
		{
			addCriterion("auditdate is not null");
			return (Criteria) this;
		}

		public Criteria andAuditdateEqualTo(String value)
		{
			addCriterion("auditdate =", value, "auditdate");
			return (Criteria) this;
		}

		public Criteria andAuditdateNotEqualTo(String value)
		{
			addCriterion("auditdate <>", value, "auditdate");
			return (Criteria) this;
		}

		public Criteria andAuditdateGreaterThan(String value)
		{
			addCriterion("auditdate >", value, "auditdate");
			return (Criteria) this;
		}

		public Criteria andAuditdateGreaterThanOrEqualTo(String value)
		{
			addCriterion("auditdate >=", value, "auditdate");
			return (Criteria) this;
		}

		public Criteria andAuditdateLessThan(String value)
		{
			addCriterion("auditdate <", value, "auditdate");
			return (Criteria) this;
		}

		public Criteria andAuditdateLessThanOrEqualTo(String value)
		{
			addCriterion("auditdate <=", value, "auditdate");
			return (Criteria) this;
		}

		public Criteria andAuditdateLike(String value)
		{
			addCriterion("auditdate like", value, "auditdate");
			return (Criteria) this;
		}

		public Criteria andAuditdateNotLike(String value)
		{
			addCriterion("auditdate not like", value, "auditdate");
			return (Criteria) this;
		}

		public Criteria andAuditdateIn(List<String> values)
		{
			addCriterion("auditdate in", values, "auditdate");
			return (Criteria) this;
		}

		public Criteria andAuditdateNotIn(List<String> values)
		{
			addCriterion("auditdate not in", values, "auditdate");
			return (Criteria) this;
		}

		public Criteria andAuditdateBetween(String value1, String value2)
		{
			addCriterion("auditdate between", value1, value2, "auditdate");
			return (Criteria) this;
		}

		public Criteria andAuditdateNotBetween(String value1, String value2)
		{
			addCriterion("auditdate not between", value1, value2, "auditdate");
			return (Criteria) this;
		}

		public Criteria andOwnerdateIsNull()
		{
			addCriterion("ownerdate is null");
			return (Criteria) this;
		}

		public Criteria andOwnerdateIsNotNull()
		{
			addCriterion("ownerdate is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerdateEqualTo(String value)
		{
			addCriterion("ownerdate =", value, "ownerdate");
			return (Criteria) this;
		}

		public Criteria andOwnerdateNotEqualTo(String value)
		{
			addCriterion("ownerdate <>", value, "ownerdate");
			return (Criteria) this;
		}

		public Criteria andOwnerdateGreaterThan(String value)
		{
			addCriterion("ownerdate >", value, "ownerdate");
			return (Criteria) this;
		}

		public Criteria andOwnerdateGreaterThanOrEqualTo(String value)
		{
			addCriterion("ownerdate >=", value, "ownerdate");
			return (Criteria) this;
		}

		public Criteria andOwnerdateLessThan(String value)
		{
			addCriterion("ownerdate <", value, "ownerdate");
			return (Criteria) this;
		}

		public Criteria andOwnerdateLessThanOrEqualTo(String value)
		{
			addCriterion("ownerdate <=", value, "ownerdate");
			return (Criteria) this;
		}

		public Criteria andOwnerdateLike(String value)
		{
			addCriterion("ownerdate like", value, "ownerdate");
			return (Criteria) this;
		}

		public Criteria andOwnerdateNotLike(String value)
		{
			addCriterion("ownerdate not like", value, "ownerdate");
			return (Criteria) this;
		}

		public Criteria andOwnerdateIn(List<String> values)
		{
			addCriterion("ownerdate in", values, "ownerdate");
			return (Criteria) this;
		}

		public Criteria andOwnerdateNotIn(List<String> values)
		{
			addCriterion("ownerdate not in", values, "ownerdate");
			return (Criteria) this;
		}

		public Criteria andOwnerdateBetween(String value1, String value2)
		{
			addCriterion("ownerdate between", value1, value2, "ownerdate");
			return (Criteria) this;
		}

		public Criteria andOwnerdateNotBetween(String value1, String value2)
		{
			addCriterion("ownerdate not between", value1, value2, "ownerdate");
			return (Criteria) this;
		}

		public Criteria andLocdateIsNull()
		{
			addCriterion("locdate is null");
			return (Criteria) this;
		}

		public Criteria andLocdateIsNotNull()
		{
			addCriterion("locdate is not null");
			return (Criteria) this;
		}

		public Criteria andLocdateEqualTo(String value)
		{
			addCriterion("locdate =", value, "locdate");
			return (Criteria) this;
		}

		public Criteria andLocdateNotEqualTo(String value)
		{
			addCriterion("locdate <>", value, "locdate");
			return (Criteria) this;
		}

		public Criteria andLocdateGreaterThan(String value)
		{
			addCriterion("locdate >", value, "locdate");
			return (Criteria) this;
		}

		public Criteria andLocdateGreaterThanOrEqualTo(String value)
		{
			addCriterion("locdate >=", value, "locdate");
			return (Criteria) this;
		}

		public Criteria andLocdateLessThan(String value)
		{
			addCriterion("locdate <", value, "locdate");
			return (Criteria) this;
		}

		public Criteria andLocdateLessThanOrEqualTo(String value)
		{
			addCriterion("locdate <=", value, "locdate");
			return (Criteria) this;
		}

		public Criteria andLocdateLike(String value)
		{
			addCriterion("locdate like", value, "locdate");
			return (Criteria) this;
		}

		public Criteria andLocdateNotLike(String value)
		{
			addCriterion("locdate not like", value, "locdate");
			return (Criteria) this;
		}

		public Criteria andLocdateIn(List<String> values)
		{
			addCriterion("locdate in", values, "locdate");
			return (Criteria) this;
		}

		public Criteria andLocdateNotIn(List<String> values)
		{
			addCriterion("locdate not in", values, "locdate");
			return (Criteria) this;
		}

		public Criteria andLocdateBetween(String value1, String value2)
		{
			addCriterion("locdate between", value1, value2, "locdate");
			return (Criteria) this;
		}

		public Criteria andLocdateNotBetween(String value1, String value2)
		{
			addCriterion("locdate not between", value1, value2, "locdate");
			return (Criteria) this;
		}

		public Criteria andGiaapproveddateIsNull()
		{
			addCriterion("giaapproveddate is null");
			return (Criteria) this;
		}

		public Criteria andGiaapproveddateIsNotNull()
		{
			addCriterion("giaapproveddate is not null");
			return (Criteria) this;
		}

		public Criteria andGiaapproveddateEqualTo(String value)
		{
			addCriterion("giaapproveddate =", value, "giaapproveddate");
			return (Criteria) this;
		}

		public Criteria andGiaapproveddateNotEqualTo(String value)
		{
			addCriterion("giaapproveddate <>", value, "giaapproveddate");
			return (Criteria) this;
		}

		public Criteria andGiaapproveddateGreaterThan(String value)
		{
			addCriterion("giaapproveddate >", value, "giaapproveddate");
			return (Criteria) this;
		}

		public Criteria andGiaapproveddateGreaterThanOrEqualTo(String value)
		{
			addCriterion("giaapproveddate >=", value, "giaapproveddate");
			return (Criteria) this;
		}

		public Criteria andGiaapproveddateLessThan(String value)
		{
			addCriterion("giaapproveddate <", value, "giaapproveddate");
			return (Criteria) this;
		}

		public Criteria andGiaapproveddateLessThanOrEqualTo(String value)
		{
			addCriterion("giaapproveddate <=", value, "giaapproveddate");
			return (Criteria) this;
		}

		public Criteria andGiaapproveddateLike(String value)
		{
			addCriterion("giaapproveddate like", value, "giaapproveddate");
			return (Criteria) this;
		}

		public Criteria andGiaapproveddateNotLike(String value)
		{
			addCriterion("giaapproveddate not like", value, "giaapproveddate");
			return (Criteria) this;
		}

		public Criteria andGiaapproveddateIn(List<String> values)
		{
			addCriterion("giaapproveddate in", values, "giaapproveddate");
			return (Criteria) this;
		}

		public Criteria andGiaapproveddateNotIn(List<String> values)
		{
			addCriterion("giaapproveddate not in", values, "giaapproveddate");
			return (Criteria) this;
		}

		public Criteria andGiaapproveddateBetween(String value1, String value2)
		{
			addCriterion("giaapproveddate between", value1, value2, "giaapproveddate");
			return (Criteria) this;
		}

		public Criteria andGiaapproveddateNotBetween(String value1, String value2)
		{
			addCriterion("giaapproveddate not between", value1, value2, "giaapproveddate");
			return (Criteria) this;
		}

		public Criteria andResultIsNull()
		{
			addCriterion("result is null");
			return (Criteria) this;
		}

		public Criteria andResultIsNotNull()
		{
			addCriterion("result is not null");
			return (Criteria) this;
		}

		public Criteria andResultEqualTo(String value)
		{
			addCriterion("result =", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultNotEqualTo(String value)
		{
			addCriterion("result <>", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultGreaterThan(String value)
		{
			addCriterion("result >", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultGreaterThanOrEqualTo(String value)
		{
			addCriterion("result >=", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultLessThan(String value)
		{
			addCriterion("result <", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultLessThanOrEqualTo(String value)
		{
			addCriterion("result <=", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultLike(String value)
		{
			addCriterion("result like", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultNotLike(String value)
		{
			addCriterion("result not like", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultIn(List<String> values)
		{
			addCriterion("result in", values, "result");
			return (Criteria) this;
		}

		public Criteria andResultNotIn(List<String> values)
		{
			addCriterion("result not in", values, "result");
			return (Criteria) this;
		}

		public Criteria andResultBetween(String value1, String value2)
		{
			addCriterion("result between", value1, value2, "result");
			return (Criteria) this;
		}

		public Criteria andResultNotBetween(String value1, String value2)
		{
			addCriterion("result not between", value1, value2, "result");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull()
		{
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull()
		{
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value)
		{
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value)
		{
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value)
		{
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value)
		{
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value)
		{
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value)
		{
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value)
		{
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value)
		{
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values)
		{
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values)
		{
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2)
		{
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2)
		{
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	public static class Criterion
	{
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition()
		{
			return condition;
		}

		public Object getValue()
		{
			return value;
		}

		public Object getSecondValue()
		{
			return secondValue;
		}

		public boolean isNoValue()
		{
			return noValue;
		}

		public boolean isSingleValue()
		{
			return singleValue;
		}

		public boolean isBetweenValue()
		{
			return betweenValue;
		}

		public boolean isListValue()
		{
			return listValue;
		}

		public String getTypeHandler()
		{
			return typeHandler;
		}

		protected Criterion(String condition)
		{
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler)
		{
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>)
			{
				this.listValue = true;
			} else
			{
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value)
		{
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler)
		{
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue)
		{
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BASKETINFO
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 31 14:41:43 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}