package ats.blockchain.web.model;

import java.math.BigDecimal;

public class Diamondsinfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.tradeid
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private Integer tradeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.basketno
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String basketno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.giano
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String giano;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.reqcode
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String reqcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.reqdate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String reqdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.resdate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String resdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.supcode
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String supcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.supname
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String supname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.productcode
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String productcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.shape
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String shape;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.size
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private BigDecimal size;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.color
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String color;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.clarity
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String clarity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.cut
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String cut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.polish
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String polish;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.symmetry
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String symmetry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.status
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.origin
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String origin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.minedate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String minedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.cutter
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String cutter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.craftsmanname
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String craftsmanname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.craftsmandate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String craftsmandate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.dealername
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String dealername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.dealerdate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String dealerdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.remark1
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String remark1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.remark2
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String remark2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.remark3
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String remark3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.remark4
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String remark4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diamondsinfo.remark5
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	private String remark5;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.tradeid
	 * @return  the value of diamondsinfo.tradeid
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public Integer getTradeid()
	{
		return tradeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.tradeid
	 * @param tradeid  the value for diamondsinfo.tradeid
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setTradeid(Integer tradeid)
	{
		this.tradeid = tradeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.basketno
	 * @return  the value of diamondsinfo.basketno
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getBasketno()
	{
		return basketno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.basketno
	 * @param basketno  the value for diamondsinfo.basketno
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setBasketno(String basketno)
	{
		this.basketno = basketno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.giano
	 * @return  the value of diamondsinfo.giano
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getGiano()
	{
		return giano;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.giano
	 * @param giano  the value for diamondsinfo.giano
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setGiano(String giano)
	{
		this.giano = giano;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.reqcode
	 * @return  the value of diamondsinfo.reqcode
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getReqcode()
	{
		return reqcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.reqcode
	 * @param reqcode  the value for diamondsinfo.reqcode
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setReqcode(String reqcode)
	{
		this.reqcode = reqcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.reqdate
	 * @return  the value of diamondsinfo.reqdate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getReqdate()
	{
		return reqdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.reqdate
	 * @param reqdate  the value for diamondsinfo.reqdate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setReqdate(String reqdate)
	{
		this.reqdate = reqdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.resdate
	 * @return  the value of diamondsinfo.resdate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getResdate()
	{
		return resdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.resdate
	 * @param resdate  the value for diamondsinfo.resdate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setResdate(String resdate)
	{
		this.resdate = resdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.supcode
	 * @return  the value of diamondsinfo.supcode
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getSupcode()
	{
		return supcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.supcode
	 * @param supcode  the value for diamondsinfo.supcode
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setSupcode(String supcode)
	{
		this.supcode = supcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.supname
	 * @return  the value of diamondsinfo.supname
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getSupname()
	{
		return supname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.supname
	 * @param supname  the value for diamondsinfo.supname
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setSupname(String supname)
	{
		this.supname = supname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.productcode
	 * @return  the value of diamondsinfo.productcode
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getProductcode()
	{
		return productcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.productcode
	 * @param productcode  the value for diamondsinfo.productcode
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setProductcode(String productcode)
	{
		this.productcode = productcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.shape
	 * @return  the value of diamondsinfo.shape
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getShape()
	{
		return shape;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.shape
	 * @param shape  the value for diamondsinfo.shape
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setShape(String shape)
	{
		this.shape = shape;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.size
	 * @return  the value of diamondsinfo.size
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public BigDecimal getSize()
	{
		return size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.size
	 * @param size  the value for diamondsinfo.size
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setSize(BigDecimal size)
	{
		this.size = size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.color
	 * @return  the value of diamondsinfo.color
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getColor()
	{
		return color;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.color
	 * @param color  the value for diamondsinfo.color
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setColor(String color)
	{
		this.color = color;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.clarity
	 * @return  the value of diamondsinfo.clarity
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getClarity()
	{
		return clarity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.clarity
	 * @param clarity  the value for diamondsinfo.clarity
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setClarity(String clarity)
	{
		this.clarity = clarity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.cut
	 * @return  the value of diamondsinfo.cut
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getCut()
	{
		return cut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.cut
	 * @param cut  the value for diamondsinfo.cut
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setCut(String cut)
	{
		this.cut = cut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.polish
	 * @return  the value of diamondsinfo.polish
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getPolish()
	{
		return polish;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.polish
	 * @param polish  the value for diamondsinfo.polish
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setPolish(String polish)
	{
		this.polish = polish;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.symmetry
	 * @return  the value of diamondsinfo.symmetry
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getSymmetry()
	{
		return symmetry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.symmetry
	 * @param symmetry  the value for diamondsinfo.symmetry
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setSymmetry(String symmetry)
	{
		this.symmetry = symmetry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.status
	 * @return  the value of diamondsinfo.status
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getStatus()
	{
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.status
	 * @param status  the value for diamondsinfo.status
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setStatus(String status)
	{
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.origin
	 * @return  the value of diamondsinfo.origin
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getOrigin()
	{
		return origin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.origin
	 * @param origin  the value for diamondsinfo.origin
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setOrigin(String origin)
	{
		this.origin = origin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.minedate
	 * @return  the value of diamondsinfo.minedate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getMinedate()
	{
		return minedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.minedate
	 * @param minedate  the value for diamondsinfo.minedate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setMinedate(String minedate)
	{
		this.minedate = minedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.cutter
	 * @return  the value of diamondsinfo.cutter
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getCutter()
	{
		return cutter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.cutter
	 * @param cutter  the value for diamondsinfo.cutter
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setCutter(String cutter)
	{
		this.cutter = cutter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.craftsmanname
	 * @return  the value of diamondsinfo.craftsmanname
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getCraftsmanname()
	{
		return craftsmanname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.craftsmanname
	 * @param craftsmanname  the value for diamondsinfo.craftsmanname
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setCraftsmanname(String craftsmanname)
	{
		this.craftsmanname = craftsmanname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.craftsmandate
	 * @return  the value of diamondsinfo.craftsmandate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getCraftsmandate()
	{
		return craftsmandate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.craftsmandate
	 * @param craftsmandate  the value for diamondsinfo.craftsmandate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setCraftsmandate(String craftsmandate)
	{
		this.craftsmandate = craftsmandate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.dealername
	 * @return  the value of diamondsinfo.dealername
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getDealername()
	{
		return dealername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.dealername
	 * @param dealername  the value for diamondsinfo.dealername
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setDealername(String dealername)
	{
		this.dealername = dealername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.dealerdate
	 * @return  the value of diamondsinfo.dealerdate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getDealerdate()
	{
		return dealerdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.dealerdate
	 * @param dealerdate  the value for diamondsinfo.dealerdate
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setDealerdate(String dealerdate)
	{
		this.dealerdate = dealerdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.remark1
	 * @return  the value of diamondsinfo.remark1
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getRemark1()
	{
		return remark1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.remark1
	 * @param remark1  the value for diamondsinfo.remark1
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setRemark1(String remark1)
	{
		this.remark1 = remark1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.remark2
	 * @return  the value of diamondsinfo.remark2
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getRemark2()
	{
		return remark2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.remark2
	 * @param remark2  the value for diamondsinfo.remark2
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setRemark2(String remark2)
	{
		this.remark2 = remark2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.remark3
	 * @return  the value of diamondsinfo.remark3
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getRemark3()
	{
		return remark3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.remark3
	 * @param remark3  the value for diamondsinfo.remark3
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setRemark3(String remark3)
	{
		this.remark3 = remark3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.remark4
	 * @return  the value of diamondsinfo.remark4
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getRemark4()
	{
		return remark4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.remark4
	 * @param remark4  the value for diamondsinfo.remark4
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setRemark4(String remark4)
	{
		this.remark4 = remark4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diamondsinfo.remark5
	 * @return  the value of diamondsinfo.remark5
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getRemark5()
	{
		return remark5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diamondsinfo.remark5
	 * @param remark5  the value for diamondsinfo.remark5
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setRemark5(String remark5)
	{
		this.remark5 = remark5;
	}
}