package ats.blockchain.web.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DiamondsinfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public DiamondsinfoExample()
	{
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setOrderByClause(String orderByClause)
	{
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public String getOrderByClause()
	{
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void setDistinct(boolean distinct)
	{
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public boolean isDistinct()
	{
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public List<Criteria> getOredCriteria()
	{
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void or(Criteria criteria)
	{
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public Criteria or()
	{
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public Criteria createCriteria()
	{
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0)
		{
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	protected Criteria createCriteriaInternal()
	{
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public void clear()
	{
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	protected abstract static class GeneratedCriteria
	{
		protected List<Criterion> criteria;

		protected GeneratedCriteria()
		{
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid()
		{
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria()
		{
			return criteria;
		}

		public List<Criterion> getCriteria()
		{
			return criteria;
		}

		protected void addCriterion(String condition)
		{
			if (condition == null)
			{
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property)
		{
			if (value == null)
			{
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property)
		{
			if (value1 == null || value2 == null)
			{
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTradeidIsNull()
		{
			addCriterion("tradeid is null");
			return (Criteria) this;
		}

		public Criteria andTradeidIsNotNull()
		{
			addCriterion("tradeid is not null");
			return (Criteria) this;
		}

		public Criteria andTradeidEqualTo(Integer value)
		{
			addCriterion("tradeid =", value, "tradeid");
			return (Criteria) this;
		}

		public Criteria andTradeidNotEqualTo(Integer value)
		{
			addCriterion("tradeid <>", value, "tradeid");
			return (Criteria) this;
		}

		public Criteria andTradeidGreaterThan(Integer value)
		{
			addCriterion("tradeid >", value, "tradeid");
			return (Criteria) this;
		}

		public Criteria andTradeidGreaterThanOrEqualTo(Integer value)
		{
			addCriterion("tradeid >=", value, "tradeid");
			return (Criteria) this;
		}

		public Criteria andTradeidLessThan(Integer value)
		{
			addCriterion("tradeid <", value, "tradeid");
			return (Criteria) this;
		}

		public Criteria andTradeidLessThanOrEqualTo(Integer value)
		{
			addCriterion("tradeid <=", value, "tradeid");
			return (Criteria) this;
		}

		public Criteria andTradeidIn(List<Integer> values)
		{
			addCriterion("tradeid in", values, "tradeid");
			return (Criteria) this;
		}

		public Criteria andTradeidNotIn(List<Integer> values)
		{
			addCriterion("tradeid not in", values, "tradeid");
			return (Criteria) this;
		}

		public Criteria andTradeidBetween(Integer value1, Integer value2)
		{
			addCriterion("tradeid between", value1, value2, "tradeid");
			return (Criteria) this;
		}

		public Criteria andTradeidNotBetween(Integer value1, Integer value2)
		{
			addCriterion("tradeid not between", value1, value2, "tradeid");
			return (Criteria) this;
		}

		public Criteria andBasketnoIsNull()
		{
			addCriterion("basketno is null");
			return (Criteria) this;
		}

		public Criteria andBasketnoIsNotNull()
		{
			addCriterion("basketno is not null");
			return (Criteria) this;
		}

		public Criteria andBasketnoEqualTo(String value)
		{
			addCriterion("basketno =", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoNotEqualTo(String value)
		{
			addCriterion("basketno <>", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoGreaterThan(String value)
		{
			addCriterion("basketno >", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoGreaterThanOrEqualTo(String value)
		{
			addCriterion("basketno >=", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoLessThan(String value)
		{
			addCriterion("basketno <", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoLessThanOrEqualTo(String value)
		{
			addCriterion("basketno <=", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoLike(String value)
		{
			addCriterion("basketno like", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoNotLike(String value)
		{
			addCriterion("basketno not like", value, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoIn(List<String> values)
		{
			addCriterion("basketno in", values, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoNotIn(List<String> values)
		{
			addCriterion("basketno not in", values, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoBetween(String value1, String value2)
		{
			addCriterion("basketno between", value1, value2, "basketno");
			return (Criteria) this;
		}

		public Criteria andBasketnoNotBetween(String value1, String value2)
		{
			addCriterion("basketno not between", value1, value2, "basketno");
			return (Criteria) this;
		}

		public Criteria andGianoIsNull()
		{
			addCriterion("giano is null");
			return (Criteria) this;
		}

		public Criteria andGianoIsNotNull()
		{
			addCriterion("giano is not null");
			return (Criteria) this;
		}

		public Criteria andGianoEqualTo(String value)
		{
			addCriterion("giano =", value, "giano");
			return (Criteria) this;
		}

		public Criteria andGianoNotEqualTo(String value)
		{
			addCriterion("giano <>", value, "giano");
			return (Criteria) this;
		}

		public Criteria andGianoGreaterThan(String value)
		{
			addCriterion("giano >", value, "giano");
			return (Criteria) this;
		}

		public Criteria andGianoGreaterThanOrEqualTo(String value)
		{
			addCriterion("giano >=", value, "giano");
			return (Criteria) this;
		}

		public Criteria andGianoLessThan(String value)
		{
			addCriterion("giano <", value, "giano");
			return (Criteria) this;
		}

		public Criteria andGianoLessThanOrEqualTo(String value)
		{
			addCriterion("giano <=", value, "giano");
			return (Criteria) this;
		}

		public Criteria andGianoLike(String value)
		{
			addCriterion("giano like", value, "giano");
			return (Criteria) this;
		}

		public Criteria andGianoNotLike(String value)
		{
			addCriterion("giano not like", value, "giano");
			return (Criteria) this;
		}

		public Criteria andGianoIn(List<String> values)
		{
			addCriterion("giano in", values, "giano");
			return (Criteria) this;
		}

		public Criteria andGianoNotIn(List<String> values)
		{
			addCriterion("giano not in", values, "giano");
			return (Criteria) this;
		}

		public Criteria andGianoBetween(String value1, String value2)
		{
			addCriterion("giano between", value1, value2, "giano");
			return (Criteria) this;
		}

		public Criteria andGianoNotBetween(String value1, String value2)
		{
			addCriterion("giano not between", value1, value2, "giano");
			return (Criteria) this;
		}

		public Criteria andReqcodeIsNull()
		{
			addCriterion("reqcode is null");
			return (Criteria) this;
		}

		public Criteria andReqcodeIsNotNull()
		{
			addCriterion("reqcode is not null");
			return (Criteria) this;
		}

		public Criteria andReqcodeEqualTo(String value)
		{
			addCriterion("reqcode =", value, "reqcode");
			return (Criteria) this;
		}

		public Criteria andReqcodeNotEqualTo(String value)
		{
			addCriterion("reqcode <>", value, "reqcode");
			return (Criteria) this;
		}

		public Criteria andReqcodeGreaterThan(String value)
		{
			addCriterion("reqcode >", value, "reqcode");
			return (Criteria) this;
		}

		public Criteria andReqcodeGreaterThanOrEqualTo(String value)
		{
			addCriterion("reqcode >=", value, "reqcode");
			return (Criteria) this;
		}

		public Criteria andReqcodeLessThan(String value)
		{
			addCriterion("reqcode <", value, "reqcode");
			return (Criteria) this;
		}

		public Criteria andReqcodeLessThanOrEqualTo(String value)
		{
			addCriterion("reqcode <=", value, "reqcode");
			return (Criteria) this;
		}

		public Criteria andReqcodeLike(String value)
		{
			addCriterion("reqcode like", value, "reqcode");
			return (Criteria) this;
		}

		public Criteria andReqcodeNotLike(String value)
		{
			addCriterion("reqcode not like", value, "reqcode");
			return (Criteria) this;
		}

		public Criteria andReqcodeIn(List<String> values)
		{
			addCriterion("reqcode in", values, "reqcode");
			return (Criteria) this;
		}

		public Criteria andReqcodeNotIn(List<String> values)
		{
			addCriterion("reqcode not in", values, "reqcode");
			return (Criteria) this;
		}

		public Criteria andReqcodeBetween(String value1, String value2)
		{
			addCriterion("reqcode between", value1, value2, "reqcode");
			return (Criteria) this;
		}

		public Criteria andReqcodeNotBetween(String value1, String value2)
		{
			addCriterion("reqcode not between", value1, value2, "reqcode");
			return (Criteria) this;
		}

		public Criteria andReqdateIsNull()
		{
			addCriterion("reqdate is null");
			return (Criteria) this;
		}

		public Criteria andReqdateIsNotNull()
		{
			addCriterion("reqdate is not null");
			return (Criteria) this;
		}

		public Criteria andReqdateEqualTo(String value)
		{
			addCriterion("reqdate =", value, "reqdate");
			return (Criteria) this;
		}

		public Criteria andReqdateNotEqualTo(String value)
		{
			addCriterion("reqdate <>", value, "reqdate");
			return (Criteria) this;
		}

		public Criteria andReqdateGreaterThan(String value)
		{
			addCriterion("reqdate >", value, "reqdate");
			return (Criteria) this;
		}

		public Criteria andReqdateGreaterThanOrEqualTo(String value)
		{
			addCriterion("reqdate >=", value, "reqdate");
			return (Criteria) this;
		}

		public Criteria andReqdateLessThan(String value)
		{
			addCriterion("reqdate <", value, "reqdate");
			return (Criteria) this;
		}

		public Criteria andReqdateLessThanOrEqualTo(String value)
		{
			addCriterion("reqdate <=", value, "reqdate");
			return (Criteria) this;
		}

		public Criteria andReqdateLike(String value)
		{
			addCriterion("reqdate like", value, "reqdate");
			return (Criteria) this;
		}

		public Criteria andReqdateNotLike(String value)
		{
			addCriterion("reqdate not like", value, "reqdate");
			return (Criteria) this;
		}

		public Criteria andReqdateIn(List<String> values)
		{
			addCriterion("reqdate in", values, "reqdate");
			return (Criteria) this;
		}

		public Criteria andReqdateNotIn(List<String> values)
		{
			addCriterion("reqdate not in", values, "reqdate");
			return (Criteria) this;
		}

		public Criteria andReqdateBetween(String value1, String value2)
		{
			addCriterion("reqdate between", value1, value2, "reqdate");
			return (Criteria) this;
		}

		public Criteria andReqdateNotBetween(String value1, String value2)
		{
			addCriterion("reqdate not between", value1, value2, "reqdate");
			return (Criteria) this;
		}

		public Criteria andResdateIsNull()
		{
			addCriterion("resdate is null");
			return (Criteria) this;
		}

		public Criteria andResdateIsNotNull()
		{
			addCriterion("resdate is not null");
			return (Criteria) this;
		}

		public Criteria andResdateEqualTo(String value)
		{
			addCriterion("resdate =", value, "resdate");
			return (Criteria) this;
		}

		public Criteria andResdateNotEqualTo(String value)
		{
			addCriterion("resdate <>", value, "resdate");
			return (Criteria) this;
		}

		public Criteria andResdateGreaterThan(String value)
		{
			addCriterion("resdate >", value, "resdate");
			return (Criteria) this;
		}

		public Criteria andResdateGreaterThanOrEqualTo(String value)
		{
			addCriterion("resdate >=", value, "resdate");
			return (Criteria) this;
		}

		public Criteria andResdateLessThan(String value)
		{
			addCriterion("resdate <", value, "resdate");
			return (Criteria) this;
		}

		public Criteria andResdateLessThanOrEqualTo(String value)
		{
			addCriterion("resdate <=", value, "resdate");
			return (Criteria) this;
		}

		public Criteria andResdateLike(String value)
		{
			addCriterion("resdate like", value, "resdate");
			return (Criteria) this;
		}

		public Criteria andResdateNotLike(String value)
		{
			addCriterion("resdate not like", value, "resdate");
			return (Criteria) this;
		}

		public Criteria andResdateIn(List<String> values)
		{
			addCriterion("resdate in", values, "resdate");
			return (Criteria) this;
		}

		public Criteria andResdateNotIn(List<String> values)
		{
			addCriterion("resdate not in", values, "resdate");
			return (Criteria) this;
		}

		public Criteria andResdateBetween(String value1, String value2)
		{
			addCriterion("resdate between", value1, value2, "resdate");
			return (Criteria) this;
		}

		public Criteria andResdateNotBetween(String value1, String value2)
		{
			addCriterion("resdate not between", value1, value2, "resdate");
			return (Criteria) this;
		}

		public Criteria andSupcodeIsNull()
		{
			addCriterion("supcode is null");
			return (Criteria) this;
		}

		public Criteria andSupcodeIsNotNull()
		{
			addCriterion("supcode is not null");
			return (Criteria) this;
		}

		public Criteria andSupcodeEqualTo(String value)
		{
			addCriterion("supcode =", value, "supcode");
			return (Criteria) this;
		}

		public Criteria andSupcodeNotEqualTo(String value)
		{
			addCriterion("supcode <>", value, "supcode");
			return (Criteria) this;
		}

		public Criteria andSupcodeGreaterThan(String value)
		{
			addCriterion("supcode >", value, "supcode");
			return (Criteria) this;
		}

		public Criteria andSupcodeGreaterThanOrEqualTo(String value)
		{
			addCriterion("supcode >=", value, "supcode");
			return (Criteria) this;
		}

		public Criteria andSupcodeLessThan(String value)
		{
			addCriterion("supcode <", value, "supcode");
			return (Criteria) this;
		}

		public Criteria andSupcodeLessThanOrEqualTo(String value)
		{
			addCriterion("supcode <=", value, "supcode");
			return (Criteria) this;
		}

		public Criteria andSupcodeLike(String value)
		{
			addCriterion("supcode like", value, "supcode");
			return (Criteria) this;
		}

		public Criteria andSupcodeNotLike(String value)
		{
			addCriterion("supcode not like", value, "supcode");
			return (Criteria) this;
		}

		public Criteria andSupcodeIn(List<String> values)
		{
			addCriterion("supcode in", values, "supcode");
			return (Criteria) this;
		}

		public Criteria andSupcodeNotIn(List<String> values)
		{
			addCriterion("supcode not in", values, "supcode");
			return (Criteria) this;
		}

		public Criteria andSupcodeBetween(String value1, String value2)
		{
			addCriterion("supcode between", value1, value2, "supcode");
			return (Criteria) this;
		}

		public Criteria andSupcodeNotBetween(String value1, String value2)
		{
			addCriterion("supcode not between", value1, value2, "supcode");
			return (Criteria) this;
		}

		public Criteria andSupnameIsNull()
		{
			addCriterion("supname is null");
			return (Criteria) this;
		}

		public Criteria andSupnameIsNotNull()
		{
			addCriterion("supname is not null");
			return (Criteria) this;
		}

		public Criteria andSupnameEqualTo(String value)
		{
			addCriterion("supname =", value, "supname");
			return (Criteria) this;
		}

		public Criteria andSupnameNotEqualTo(String value)
		{
			addCriterion("supname <>", value, "supname");
			return (Criteria) this;
		}

		public Criteria andSupnameGreaterThan(String value)
		{
			addCriterion("supname >", value, "supname");
			return (Criteria) this;
		}

		public Criteria andSupnameGreaterThanOrEqualTo(String value)
		{
			addCriterion("supname >=", value, "supname");
			return (Criteria) this;
		}

		public Criteria andSupnameLessThan(String value)
		{
			addCriterion("supname <", value, "supname");
			return (Criteria) this;
		}

		public Criteria andSupnameLessThanOrEqualTo(String value)
		{
			addCriterion("supname <=", value, "supname");
			return (Criteria) this;
		}

		public Criteria andSupnameLike(String value)
		{
			addCriterion("supname like", value, "supname");
			return (Criteria) this;
		}

		public Criteria andSupnameNotLike(String value)
		{
			addCriterion("supname not like", value, "supname");
			return (Criteria) this;
		}

		public Criteria andSupnameIn(List<String> values)
		{
			addCriterion("supname in", values, "supname");
			return (Criteria) this;
		}

		public Criteria andSupnameNotIn(List<String> values)
		{
			addCriterion("supname not in", values, "supname");
			return (Criteria) this;
		}

		public Criteria andSupnameBetween(String value1, String value2)
		{
			addCriterion("supname between", value1, value2, "supname");
			return (Criteria) this;
		}

		public Criteria andSupnameNotBetween(String value1, String value2)
		{
			addCriterion("supname not between", value1, value2, "supname");
			return (Criteria) this;
		}

		public Criteria andProductcodeIsNull()
		{
			addCriterion("productcode is null");
			return (Criteria) this;
		}

		public Criteria andProductcodeIsNotNull()
		{
			addCriterion("productcode is not null");
			return (Criteria) this;
		}

		public Criteria andProductcodeEqualTo(String value)
		{
			addCriterion("productcode =", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeNotEqualTo(String value)
		{
			addCriterion("productcode <>", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeGreaterThan(String value)
		{
			addCriterion("productcode >", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeGreaterThanOrEqualTo(String value)
		{
			addCriterion("productcode >=", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeLessThan(String value)
		{
			addCriterion("productcode <", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeLessThanOrEqualTo(String value)
		{
			addCriterion("productcode <=", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeLike(String value)
		{
			addCriterion("productcode like", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeNotLike(String value)
		{
			addCriterion("productcode not like", value, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeIn(List<String> values)
		{
			addCriterion("productcode in", values, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeNotIn(List<String> values)
		{
			addCriterion("productcode not in", values, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeBetween(String value1, String value2)
		{
			addCriterion("productcode between", value1, value2, "productcode");
			return (Criteria) this;
		}

		public Criteria andProductcodeNotBetween(String value1, String value2)
		{
			addCriterion("productcode not between", value1, value2, "productcode");
			return (Criteria) this;
		}

		public Criteria andShapeIsNull()
		{
			addCriterion("shape is null");
			return (Criteria) this;
		}

		public Criteria andShapeIsNotNull()
		{
			addCriterion("shape is not null");
			return (Criteria) this;
		}

		public Criteria andShapeEqualTo(String value)
		{
			addCriterion("shape =", value, "shape");
			return (Criteria) this;
		}

		public Criteria andShapeNotEqualTo(String value)
		{
			addCriterion("shape <>", value, "shape");
			return (Criteria) this;
		}

		public Criteria andShapeGreaterThan(String value)
		{
			addCriterion("shape >", value, "shape");
			return (Criteria) this;
		}

		public Criteria andShapeGreaterThanOrEqualTo(String value)
		{
			addCriterion("shape >=", value, "shape");
			return (Criteria) this;
		}

		public Criteria andShapeLessThan(String value)
		{
			addCriterion("shape <", value, "shape");
			return (Criteria) this;
		}

		public Criteria andShapeLessThanOrEqualTo(String value)
		{
			addCriterion("shape <=", value, "shape");
			return (Criteria) this;
		}

		public Criteria andShapeLike(String value)
		{
			addCriterion("shape like", value, "shape");
			return (Criteria) this;
		}

		public Criteria andShapeNotLike(String value)
		{
			addCriterion("shape not like", value, "shape");
			return (Criteria) this;
		}

		public Criteria andShapeIn(List<String> values)
		{
			addCriterion("shape in", values, "shape");
			return (Criteria) this;
		}

		public Criteria andShapeNotIn(List<String> values)
		{
			addCriterion("shape not in", values, "shape");
			return (Criteria) this;
		}

		public Criteria andShapeBetween(String value1, String value2)
		{
			addCriterion("shape between", value1, value2, "shape");
			return (Criteria) this;
		}

		public Criteria andShapeNotBetween(String value1, String value2)
		{
			addCriterion("shape not between", value1, value2, "shape");
			return (Criteria) this;
		}

		public Criteria andSizeIsNull()
		{
			addCriterion("size is null");
			return (Criteria) this;
		}

		public Criteria andSizeIsNotNull()
		{
			addCriterion("size is not null");
			return (Criteria) this;
		}

		public Criteria andSizeEqualTo(BigDecimal value)
		{
			addCriterion("size =", value, "size");
			return (Criteria) this;
		}

		public Criteria andSizeNotEqualTo(BigDecimal value)
		{
			addCriterion("size <>", value, "size");
			return (Criteria) this;
		}

		public Criteria andSizeGreaterThan(BigDecimal value)
		{
			addCriterion("size >", value, "size");
			return (Criteria) this;
		}

		public Criteria andSizeGreaterThanOrEqualTo(BigDecimal value)
		{
			addCriterion("size >=", value, "size");
			return (Criteria) this;
		}

		public Criteria andSizeLessThan(BigDecimal value)
		{
			addCriterion("size <", value, "size");
			return (Criteria) this;
		}

		public Criteria andSizeLessThanOrEqualTo(BigDecimal value)
		{
			addCriterion("size <=", value, "size");
			return (Criteria) this;
		}

		public Criteria andSizeIn(List<BigDecimal> values)
		{
			addCriterion("size in", values, "size");
			return (Criteria) this;
		}

		public Criteria andSizeNotIn(List<BigDecimal> values)
		{
			addCriterion("size not in", values, "size");
			return (Criteria) this;
		}

		public Criteria andSizeBetween(BigDecimal value1, BigDecimal value2)
		{
			addCriterion("size between", value1, value2, "size");
			return (Criteria) this;
		}

		public Criteria andSizeNotBetween(BigDecimal value1, BigDecimal value2)
		{
			addCriterion("size not between", value1, value2, "size");
			return (Criteria) this;
		}

		public Criteria andColorIsNull()
		{
			addCriterion("color is null");
			return (Criteria) this;
		}

		public Criteria andColorIsNotNull()
		{
			addCriterion("color is not null");
			return (Criteria) this;
		}

		public Criteria andColorEqualTo(String value)
		{
			addCriterion("color =", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotEqualTo(String value)
		{
			addCriterion("color <>", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorGreaterThan(String value)
		{
			addCriterion("color >", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorGreaterThanOrEqualTo(String value)
		{
			addCriterion("color >=", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorLessThan(String value)
		{
			addCriterion("color <", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorLessThanOrEqualTo(String value)
		{
			addCriterion("color <=", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorLike(String value)
		{
			addCriterion("color like", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotLike(String value)
		{
			addCriterion("color not like", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorIn(List<String> values)
		{
			addCriterion("color in", values, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotIn(List<String> values)
		{
			addCriterion("color not in", values, "color");
			return (Criteria) this;
		}

		public Criteria andColorBetween(String value1, String value2)
		{
			addCriterion("color between", value1, value2, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotBetween(String value1, String value2)
		{
			addCriterion("color not between", value1, value2, "color");
			return (Criteria) this;
		}

		public Criteria andClarityIsNull()
		{
			addCriterion("clarity is null");
			return (Criteria) this;
		}

		public Criteria andClarityIsNotNull()
		{
			addCriterion("clarity is not null");
			return (Criteria) this;
		}

		public Criteria andClarityEqualTo(String value)
		{
			addCriterion("clarity =", value, "clarity");
			return (Criteria) this;
		}

		public Criteria andClarityNotEqualTo(String value)
		{
			addCriterion("clarity <>", value, "clarity");
			return (Criteria) this;
		}

		public Criteria andClarityGreaterThan(String value)
		{
			addCriterion("clarity >", value, "clarity");
			return (Criteria) this;
		}

		public Criteria andClarityGreaterThanOrEqualTo(String value)
		{
			addCriterion("clarity >=", value, "clarity");
			return (Criteria) this;
		}

		public Criteria andClarityLessThan(String value)
		{
			addCriterion("clarity <", value, "clarity");
			return (Criteria) this;
		}

		public Criteria andClarityLessThanOrEqualTo(String value)
		{
			addCriterion("clarity <=", value, "clarity");
			return (Criteria) this;
		}

		public Criteria andClarityLike(String value)
		{
			addCriterion("clarity like", value, "clarity");
			return (Criteria) this;
		}

		public Criteria andClarityNotLike(String value)
		{
			addCriterion("clarity not like", value, "clarity");
			return (Criteria) this;
		}

		public Criteria andClarityIn(List<String> values)
		{
			addCriterion("clarity in", values, "clarity");
			return (Criteria) this;
		}

		public Criteria andClarityNotIn(List<String> values)
		{
			addCriterion("clarity not in", values, "clarity");
			return (Criteria) this;
		}

		public Criteria andClarityBetween(String value1, String value2)
		{
			addCriterion("clarity between", value1, value2, "clarity");
			return (Criteria) this;
		}

		public Criteria andClarityNotBetween(String value1, String value2)
		{
			addCriterion("clarity not between", value1, value2, "clarity");
			return (Criteria) this;
		}

		public Criteria andCutIsNull()
		{
			addCriterion("cut is null");
			return (Criteria) this;
		}

		public Criteria andCutIsNotNull()
		{
			addCriterion("cut is not null");
			return (Criteria) this;
		}

		public Criteria andCutEqualTo(String value)
		{
			addCriterion("cut =", value, "cut");
			return (Criteria) this;
		}

		public Criteria andCutNotEqualTo(String value)
		{
			addCriterion("cut <>", value, "cut");
			return (Criteria) this;
		}

		public Criteria andCutGreaterThan(String value)
		{
			addCriterion("cut >", value, "cut");
			return (Criteria) this;
		}

		public Criteria andCutGreaterThanOrEqualTo(String value)
		{
			addCriterion("cut >=", value, "cut");
			return (Criteria) this;
		}

		public Criteria andCutLessThan(String value)
		{
			addCriterion("cut <", value, "cut");
			return (Criteria) this;
		}

		public Criteria andCutLessThanOrEqualTo(String value)
		{
			addCriterion("cut <=", value, "cut");
			return (Criteria) this;
		}

		public Criteria andCutLike(String value)
		{
			addCriterion("cut like", value, "cut");
			return (Criteria) this;
		}

		public Criteria andCutNotLike(String value)
		{
			addCriterion("cut not like", value, "cut");
			return (Criteria) this;
		}

		public Criteria andCutIn(List<String> values)
		{
			addCriterion("cut in", values, "cut");
			return (Criteria) this;
		}

		public Criteria andCutNotIn(List<String> values)
		{
			addCriterion("cut not in", values, "cut");
			return (Criteria) this;
		}

		public Criteria andCutBetween(String value1, String value2)
		{
			addCriterion("cut between", value1, value2, "cut");
			return (Criteria) this;
		}

		public Criteria andCutNotBetween(String value1, String value2)
		{
			addCriterion("cut not between", value1, value2, "cut");
			return (Criteria) this;
		}

		public Criteria andPolishIsNull()
		{
			addCriterion("polish is null");
			return (Criteria) this;
		}

		public Criteria andPolishIsNotNull()
		{
			addCriterion("polish is not null");
			return (Criteria) this;
		}

		public Criteria andPolishEqualTo(String value)
		{
			addCriterion("polish =", value, "polish");
			return (Criteria) this;
		}

		public Criteria andPolishNotEqualTo(String value)
		{
			addCriterion("polish <>", value, "polish");
			return (Criteria) this;
		}

		public Criteria andPolishGreaterThan(String value)
		{
			addCriterion("polish >", value, "polish");
			return (Criteria) this;
		}

		public Criteria andPolishGreaterThanOrEqualTo(String value)
		{
			addCriterion("polish >=", value, "polish");
			return (Criteria) this;
		}

		public Criteria andPolishLessThan(String value)
		{
			addCriterion("polish <", value, "polish");
			return (Criteria) this;
		}

		public Criteria andPolishLessThanOrEqualTo(String value)
		{
			addCriterion("polish <=", value, "polish");
			return (Criteria) this;
		}

		public Criteria andPolishLike(String value)
		{
			addCriterion("polish like", value, "polish");
			return (Criteria) this;
		}

		public Criteria andPolishNotLike(String value)
		{
			addCriterion("polish not like", value, "polish");
			return (Criteria) this;
		}

		public Criteria andPolishIn(List<String> values)
		{
			addCriterion("polish in", values, "polish");
			return (Criteria) this;
		}

		public Criteria andPolishNotIn(List<String> values)
		{
			addCriterion("polish not in", values, "polish");
			return (Criteria) this;
		}

		public Criteria andPolishBetween(String value1, String value2)
		{
			addCriterion("polish between", value1, value2, "polish");
			return (Criteria) this;
		}

		public Criteria andPolishNotBetween(String value1, String value2)
		{
			addCriterion("polish not between", value1, value2, "polish");
			return (Criteria) this;
		}

		public Criteria andSymmetryIsNull()
		{
			addCriterion("symmetry is null");
			return (Criteria) this;
		}

		public Criteria andSymmetryIsNotNull()
		{
			addCriterion("symmetry is not null");
			return (Criteria) this;
		}

		public Criteria andSymmetryEqualTo(String value)
		{
			addCriterion("symmetry =", value, "symmetry");
			return (Criteria) this;
		}

		public Criteria andSymmetryNotEqualTo(String value)
		{
			addCriterion("symmetry <>", value, "symmetry");
			return (Criteria) this;
		}

		public Criteria andSymmetryGreaterThan(String value)
		{
			addCriterion("symmetry >", value, "symmetry");
			return (Criteria) this;
		}

		public Criteria andSymmetryGreaterThanOrEqualTo(String value)
		{
			addCriterion("symmetry >=", value, "symmetry");
			return (Criteria) this;
		}

		public Criteria andSymmetryLessThan(String value)
		{
			addCriterion("symmetry <", value, "symmetry");
			return (Criteria) this;
		}

		public Criteria andSymmetryLessThanOrEqualTo(String value)
		{
			addCriterion("symmetry <=", value, "symmetry");
			return (Criteria) this;
		}

		public Criteria andSymmetryLike(String value)
		{
			addCriterion("symmetry like", value, "symmetry");
			return (Criteria) this;
		}

		public Criteria andSymmetryNotLike(String value)
		{
			addCriterion("symmetry not like", value, "symmetry");
			return (Criteria) this;
		}

		public Criteria andSymmetryIn(List<String> values)
		{
			addCriterion("symmetry in", values, "symmetry");
			return (Criteria) this;
		}

		public Criteria andSymmetryNotIn(List<String> values)
		{
			addCriterion("symmetry not in", values, "symmetry");
			return (Criteria) this;
		}

		public Criteria andSymmetryBetween(String value1, String value2)
		{
			addCriterion("symmetry between", value1, value2, "symmetry");
			return (Criteria) this;
		}

		public Criteria andSymmetryNotBetween(String value1, String value2)
		{
			addCriterion("symmetry not between", value1, value2, "symmetry");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull()
		{
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull()
		{
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value)
		{
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value)
		{
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value)
		{
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value)
		{
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value)
		{
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value)
		{
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value)
		{
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value)
		{
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values)
		{
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values)
		{
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2)
		{
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2)
		{
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andOriginIsNull()
		{
			addCriterion("origin is null");
			return (Criteria) this;
		}

		public Criteria andOriginIsNotNull()
		{
			addCriterion("origin is not null");
			return (Criteria) this;
		}

		public Criteria andOriginEqualTo(String value)
		{
			addCriterion("origin =", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginNotEqualTo(String value)
		{
			addCriterion("origin <>", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginGreaterThan(String value)
		{
			addCriterion("origin >", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginGreaterThanOrEqualTo(String value)
		{
			addCriterion("origin >=", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginLessThan(String value)
		{
			addCriterion("origin <", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginLessThanOrEqualTo(String value)
		{
			addCriterion("origin <=", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginLike(String value)
		{
			addCriterion("origin like", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginNotLike(String value)
		{
			addCriterion("origin not like", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginIn(List<String> values)
		{
			addCriterion("origin in", values, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginNotIn(List<String> values)
		{
			addCriterion("origin not in", values, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginBetween(String value1, String value2)
		{
			addCriterion("origin between", value1, value2, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginNotBetween(String value1, String value2)
		{
			addCriterion("origin not between", value1, value2, "origin");
			return (Criteria) this;
		}

		public Criteria andMinedateIsNull()
		{
			addCriterion("minedate is null");
			return (Criteria) this;
		}

		public Criteria andMinedateIsNotNull()
		{
			addCriterion("minedate is not null");
			return (Criteria) this;
		}

		public Criteria andMinedateEqualTo(String value)
		{
			addCriterion("minedate =", value, "minedate");
			return (Criteria) this;
		}

		public Criteria andMinedateNotEqualTo(String value)
		{
			addCriterion("minedate <>", value, "minedate");
			return (Criteria) this;
		}

		public Criteria andMinedateGreaterThan(String value)
		{
			addCriterion("minedate >", value, "minedate");
			return (Criteria) this;
		}

		public Criteria andMinedateGreaterThanOrEqualTo(String value)
		{
			addCriterion("minedate >=", value, "minedate");
			return (Criteria) this;
		}

		public Criteria andMinedateLessThan(String value)
		{
			addCriterion("minedate <", value, "minedate");
			return (Criteria) this;
		}

		public Criteria andMinedateLessThanOrEqualTo(String value)
		{
			addCriterion("minedate <=", value, "minedate");
			return (Criteria) this;
		}

		public Criteria andMinedateLike(String value)
		{
			addCriterion("minedate like", value, "minedate");
			return (Criteria) this;
		}

		public Criteria andMinedateNotLike(String value)
		{
			addCriterion("minedate not like", value, "minedate");
			return (Criteria) this;
		}

		public Criteria andMinedateIn(List<String> values)
		{
			addCriterion("minedate in", values, "minedate");
			return (Criteria) this;
		}

		public Criteria andMinedateNotIn(List<String> values)
		{
			addCriterion("minedate not in", values, "minedate");
			return (Criteria) this;
		}

		public Criteria andMinedateBetween(String value1, String value2)
		{
			addCriterion("minedate between", value1, value2, "minedate");
			return (Criteria) this;
		}

		public Criteria andMinedateNotBetween(String value1, String value2)
		{
			addCriterion("minedate not between", value1, value2, "minedate");
			return (Criteria) this;
		}

		public Criteria andCutterIsNull()
		{
			addCriterion("cutter is null");
			return (Criteria) this;
		}

		public Criteria andCutterIsNotNull()
		{
			addCriterion("cutter is not null");
			return (Criteria) this;
		}

		public Criteria andCutterEqualTo(String value)
		{
			addCriterion("cutter =", value, "cutter");
			return (Criteria) this;
		}

		public Criteria andCutterNotEqualTo(String value)
		{
			addCriterion("cutter <>", value, "cutter");
			return (Criteria) this;
		}

		public Criteria andCutterGreaterThan(String value)
		{
			addCriterion("cutter >", value, "cutter");
			return (Criteria) this;
		}

		public Criteria andCutterGreaterThanOrEqualTo(String value)
		{
			addCriterion("cutter >=", value, "cutter");
			return (Criteria) this;
		}

		public Criteria andCutterLessThan(String value)
		{
			addCriterion("cutter <", value, "cutter");
			return (Criteria) this;
		}

		public Criteria andCutterLessThanOrEqualTo(String value)
		{
			addCriterion("cutter <=", value, "cutter");
			return (Criteria) this;
		}

		public Criteria andCutterLike(String value)
		{
			addCriterion("cutter like", value, "cutter");
			return (Criteria) this;
		}

		public Criteria andCutterNotLike(String value)
		{
			addCriterion("cutter not like", value, "cutter");
			return (Criteria) this;
		}

		public Criteria andCutterIn(List<String> values)
		{
			addCriterion("cutter in", values, "cutter");
			return (Criteria) this;
		}

		public Criteria andCutterNotIn(List<String> values)
		{
			addCriterion("cutter not in", values, "cutter");
			return (Criteria) this;
		}

		public Criteria andCutterBetween(String value1, String value2)
		{
			addCriterion("cutter between", value1, value2, "cutter");
			return (Criteria) this;
		}

		public Criteria andCutterNotBetween(String value1, String value2)
		{
			addCriterion("cutter not between", value1, value2, "cutter");
			return (Criteria) this;
		}

		public Criteria andCraftsmannameIsNull()
		{
			addCriterion("craftsmanname is null");
			return (Criteria) this;
		}

		public Criteria andCraftsmannameIsNotNull()
		{
			addCriterion("craftsmanname is not null");
			return (Criteria) this;
		}

		public Criteria andCraftsmannameEqualTo(String value)
		{
			addCriterion("craftsmanname =", value, "craftsmanname");
			return (Criteria) this;
		}

		public Criteria andCraftsmannameNotEqualTo(String value)
		{
			addCriterion("craftsmanname <>", value, "craftsmanname");
			return (Criteria) this;
		}

		public Criteria andCraftsmannameGreaterThan(String value)
		{
			addCriterion("craftsmanname >", value, "craftsmanname");
			return (Criteria) this;
		}

		public Criteria andCraftsmannameGreaterThanOrEqualTo(String value)
		{
			addCriterion("craftsmanname >=", value, "craftsmanname");
			return (Criteria) this;
		}

		public Criteria andCraftsmannameLessThan(String value)
		{
			addCriterion("craftsmanname <", value, "craftsmanname");
			return (Criteria) this;
		}

		public Criteria andCraftsmannameLessThanOrEqualTo(String value)
		{
			addCriterion("craftsmanname <=", value, "craftsmanname");
			return (Criteria) this;
		}

		public Criteria andCraftsmannameLike(String value)
		{
			addCriterion("craftsmanname like", value, "craftsmanname");
			return (Criteria) this;
		}

		public Criteria andCraftsmannameNotLike(String value)
		{
			addCriterion("craftsmanname not like", value, "craftsmanname");
			return (Criteria) this;
		}

		public Criteria andCraftsmannameIn(List<String> values)
		{
			addCriterion("craftsmanname in", values, "craftsmanname");
			return (Criteria) this;
		}

		public Criteria andCraftsmannameNotIn(List<String> values)
		{
			addCriterion("craftsmanname not in", values, "craftsmanname");
			return (Criteria) this;
		}

		public Criteria andCraftsmannameBetween(String value1, String value2)
		{
			addCriterion("craftsmanname between", value1, value2, "craftsmanname");
			return (Criteria) this;
		}

		public Criteria andCraftsmannameNotBetween(String value1, String value2)
		{
			addCriterion("craftsmanname not between", value1, value2, "craftsmanname");
			return (Criteria) this;
		}

		public Criteria andCraftsmandateIsNull()
		{
			addCriterion("craftsmandate is null");
			return (Criteria) this;
		}

		public Criteria andCraftsmandateIsNotNull()
		{
			addCriterion("craftsmandate is not null");
			return (Criteria) this;
		}

		public Criteria andCraftsmandateEqualTo(String value)
		{
			addCriterion("craftsmandate =", value, "craftsmandate");
			return (Criteria) this;
		}

		public Criteria andCraftsmandateNotEqualTo(String value)
		{
			addCriterion("craftsmandate <>", value, "craftsmandate");
			return (Criteria) this;
		}

		public Criteria andCraftsmandateGreaterThan(String value)
		{
			addCriterion("craftsmandate >", value, "craftsmandate");
			return (Criteria) this;
		}

		public Criteria andCraftsmandateGreaterThanOrEqualTo(String value)
		{
			addCriterion("craftsmandate >=", value, "craftsmandate");
			return (Criteria) this;
		}

		public Criteria andCraftsmandateLessThan(String value)
		{
			addCriterion("craftsmandate <", value, "craftsmandate");
			return (Criteria) this;
		}

		public Criteria andCraftsmandateLessThanOrEqualTo(String value)
		{
			addCriterion("craftsmandate <=", value, "craftsmandate");
			return (Criteria) this;
		}

		public Criteria andCraftsmandateLike(String value)
		{
			addCriterion("craftsmandate like", value, "craftsmandate");
			return (Criteria) this;
		}

		public Criteria andCraftsmandateNotLike(String value)
		{
			addCriterion("craftsmandate not like", value, "craftsmandate");
			return (Criteria) this;
		}

		public Criteria andCraftsmandateIn(List<String> values)
		{
			addCriterion("craftsmandate in", values, "craftsmandate");
			return (Criteria) this;
		}

		public Criteria andCraftsmandateNotIn(List<String> values)
		{
			addCriterion("craftsmandate not in", values, "craftsmandate");
			return (Criteria) this;
		}

		public Criteria andCraftsmandateBetween(String value1, String value2)
		{
			addCriterion("craftsmandate between", value1, value2, "craftsmandate");
			return (Criteria) this;
		}

		public Criteria andCraftsmandateNotBetween(String value1, String value2)
		{
			addCriterion("craftsmandate not between", value1, value2, "craftsmandate");
			return (Criteria) this;
		}

		public Criteria andDealernameIsNull()
		{
			addCriterion("dealername is null");
			return (Criteria) this;
		}

		public Criteria andDealernameIsNotNull()
		{
			addCriterion("dealername is not null");
			return (Criteria) this;
		}

		public Criteria andDealernameEqualTo(String value)
		{
			addCriterion("dealername =", value, "dealername");
			return (Criteria) this;
		}

		public Criteria andDealernameNotEqualTo(String value)
		{
			addCriterion("dealername <>", value, "dealername");
			return (Criteria) this;
		}

		public Criteria andDealernameGreaterThan(String value)
		{
			addCriterion("dealername >", value, "dealername");
			return (Criteria) this;
		}

		public Criteria andDealernameGreaterThanOrEqualTo(String value)
		{
			addCriterion("dealername >=", value, "dealername");
			return (Criteria) this;
		}

		public Criteria andDealernameLessThan(String value)
		{
			addCriterion("dealername <", value, "dealername");
			return (Criteria) this;
		}

		public Criteria andDealernameLessThanOrEqualTo(String value)
		{
			addCriterion("dealername <=", value, "dealername");
			return (Criteria) this;
		}

		public Criteria andDealernameLike(String value)
		{
			addCriterion("dealername like", value, "dealername");
			return (Criteria) this;
		}

		public Criteria andDealernameNotLike(String value)
		{
			addCriterion("dealername not like", value, "dealername");
			return (Criteria) this;
		}

		public Criteria andDealernameIn(List<String> values)
		{
			addCriterion("dealername in", values, "dealername");
			return (Criteria) this;
		}

		public Criteria andDealernameNotIn(List<String> values)
		{
			addCriterion("dealername not in", values, "dealername");
			return (Criteria) this;
		}

		public Criteria andDealernameBetween(String value1, String value2)
		{
			addCriterion("dealername between", value1, value2, "dealername");
			return (Criteria) this;
		}

		public Criteria andDealernameNotBetween(String value1, String value2)
		{
			addCriterion("dealername not between", value1, value2, "dealername");
			return (Criteria) this;
		}

		public Criteria andDealerdateIsNull()
		{
			addCriterion("dealerdate is null");
			return (Criteria) this;
		}

		public Criteria andDealerdateIsNotNull()
		{
			addCriterion("dealerdate is not null");
			return (Criteria) this;
		}

		public Criteria andDealerdateEqualTo(String value)
		{
			addCriterion("dealerdate =", value, "dealerdate");
			return (Criteria) this;
		}

		public Criteria andDealerdateNotEqualTo(String value)
		{
			addCriterion("dealerdate <>", value, "dealerdate");
			return (Criteria) this;
		}

		public Criteria andDealerdateGreaterThan(String value)
		{
			addCriterion("dealerdate >", value, "dealerdate");
			return (Criteria) this;
		}

		public Criteria andDealerdateGreaterThanOrEqualTo(String value)
		{
			addCriterion("dealerdate >=", value, "dealerdate");
			return (Criteria) this;
		}

		public Criteria andDealerdateLessThan(String value)
		{
			addCriterion("dealerdate <", value, "dealerdate");
			return (Criteria) this;
		}

		public Criteria andDealerdateLessThanOrEqualTo(String value)
		{
			addCriterion("dealerdate <=", value, "dealerdate");
			return (Criteria) this;
		}

		public Criteria andDealerdateLike(String value)
		{
			addCriterion("dealerdate like", value, "dealerdate");
			return (Criteria) this;
		}

		public Criteria andDealerdateNotLike(String value)
		{
			addCriterion("dealerdate not like", value, "dealerdate");
			return (Criteria) this;
		}

		public Criteria andDealerdateIn(List<String> values)
		{
			addCriterion("dealerdate in", values, "dealerdate");
			return (Criteria) this;
		}

		public Criteria andDealerdateNotIn(List<String> values)
		{
			addCriterion("dealerdate not in", values, "dealerdate");
			return (Criteria) this;
		}

		public Criteria andDealerdateBetween(String value1, String value2)
		{
			addCriterion("dealerdate between", value1, value2, "dealerdate");
			return (Criteria) this;
		}

		public Criteria andDealerdateNotBetween(String value1, String value2)
		{
			addCriterion("dealerdate not between", value1, value2, "dealerdate");
			return (Criteria) this;
		}

		public Criteria andRemark1IsNull()
		{
			addCriterion("remark1 is null");
			return (Criteria) this;
		}

		public Criteria andRemark1IsNotNull()
		{
			addCriterion("remark1 is not null");
			return (Criteria) this;
		}

		public Criteria andRemark1EqualTo(String value)
		{
			addCriterion("remark1 =", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1NotEqualTo(String value)
		{
			addCriterion("remark1 <>", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1GreaterThan(String value)
		{
			addCriterion("remark1 >", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1GreaterThanOrEqualTo(String value)
		{
			addCriterion("remark1 >=", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1LessThan(String value)
		{
			addCriterion("remark1 <", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1LessThanOrEqualTo(String value)
		{
			addCriterion("remark1 <=", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1Like(String value)
		{
			addCriterion("remark1 like", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1NotLike(String value)
		{
			addCriterion("remark1 not like", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1In(List<String> values)
		{
			addCriterion("remark1 in", values, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1NotIn(List<String> values)
		{
			addCriterion("remark1 not in", values, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1Between(String value1, String value2)
		{
			addCriterion("remark1 between", value1, value2, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1NotBetween(String value1, String value2)
		{
			addCriterion("remark1 not between", value1, value2, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark2IsNull()
		{
			addCriterion("remark2 is null");
			return (Criteria) this;
		}

		public Criteria andRemark2IsNotNull()
		{
			addCriterion("remark2 is not null");
			return (Criteria) this;
		}

		public Criteria andRemark2EqualTo(String value)
		{
			addCriterion("remark2 =", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2NotEqualTo(String value)
		{
			addCriterion("remark2 <>", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2GreaterThan(String value)
		{
			addCriterion("remark2 >", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2GreaterThanOrEqualTo(String value)
		{
			addCriterion("remark2 >=", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2LessThan(String value)
		{
			addCriterion("remark2 <", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2LessThanOrEqualTo(String value)
		{
			addCriterion("remark2 <=", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2Like(String value)
		{
			addCriterion("remark2 like", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2NotLike(String value)
		{
			addCriterion("remark2 not like", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2In(List<String> values)
		{
			addCriterion("remark2 in", values, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2NotIn(List<String> values)
		{
			addCriterion("remark2 not in", values, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2Between(String value1, String value2)
		{
			addCriterion("remark2 between", value1, value2, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2NotBetween(String value1, String value2)
		{
			addCriterion("remark2 not between", value1, value2, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark3IsNull()
		{
			addCriterion("remark3 is null");
			return (Criteria) this;
		}

		public Criteria andRemark3IsNotNull()
		{
			addCriterion("remark3 is not null");
			return (Criteria) this;
		}

		public Criteria andRemark3EqualTo(String value)
		{
			addCriterion("remark3 =", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3NotEqualTo(String value)
		{
			addCriterion("remark3 <>", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3GreaterThan(String value)
		{
			addCriterion("remark3 >", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3GreaterThanOrEqualTo(String value)
		{
			addCriterion("remark3 >=", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3LessThan(String value)
		{
			addCriterion("remark3 <", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3LessThanOrEqualTo(String value)
		{
			addCriterion("remark3 <=", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3Like(String value)
		{
			addCriterion("remark3 like", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3NotLike(String value)
		{
			addCriterion("remark3 not like", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3In(List<String> values)
		{
			addCriterion("remark3 in", values, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3NotIn(List<String> values)
		{
			addCriterion("remark3 not in", values, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3Between(String value1, String value2)
		{
			addCriterion("remark3 between", value1, value2, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3NotBetween(String value1, String value2)
		{
			addCriterion("remark3 not between", value1, value2, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark4IsNull()
		{
			addCriterion("remark4 is null");
			return (Criteria) this;
		}

		public Criteria andRemark4IsNotNull()
		{
			addCriterion("remark4 is not null");
			return (Criteria) this;
		}

		public Criteria andRemark4EqualTo(String value)
		{
			addCriterion("remark4 =", value, "remark4");
			return (Criteria) this;
		}

		public Criteria andRemark4NotEqualTo(String value)
		{
			addCriterion("remark4 <>", value, "remark4");
			return (Criteria) this;
		}

		public Criteria andRemark4GreaterThan(String value)
		{
			addCriterion("remark4 >", value, "remark4");
			return (Criteria) this;
		}

		public Criteria andRemark4GreaterThanOrEqualTo(String value)
		{
			addCriterion("remark4 >=", value, "remark4");
			return (Criteria) this;
		}

		public Criteria andRemark4LessThan(String value)
		{
			addCriterion("remark4 <", value, "remark4");
			return (Criteria) this;
		}

		public Criteria andRemark4LessThanOrEqualTo(String value)
		{
			addCriterion("remark4 <=", value, "remark4");
			return (Criteria) this;
		}

		public Criteria andRemark4Like(String value)
		{
			addCriterion("remark4 like", value, "remark4");
			return (Criteria) this;
		}

		public Criteria andRemark4NotLike(String value)
		{
			addCriterion("remark4 not like", value, "remark4");
			return (Criteria) this;
		}

		public Criteria andRemark4In(List<String> values)
		{
			addCriterion("remark4 in", values, "remark4");
			return (Criteria) this;
		}

		public Criteria andRemark4NotIn(List<String> values)
		{
			addCriterion("remark4 not in", values, "remark4");
			return (Criteria) this;
		}

		public Criteria andRemark4Between(String value1, String value2)
		{
			addCriterion("remark4 between", value1, value2, "remark4");
			return (Criteria) this;
		}

		public Criteria andRemark4NotBetween(String value1, String value2)
		{
			addCriterion("remark4 not between", value1, value2, "remark4");
			return (Criteria) this;
		}

		public Criteria andRemark5IsNull()
		{
			addCriterion("remark5 is null");
			return (Criteria) this;
		}

		public Criteria andRemark5IsNotNull()
		{
			addCriterion("remark5 is not null");
			return (Criteria) this;
		}

		public Criteria andRemark5EqualTo(String value)
		{
			addCriterion("remark5 =", value, "remark5");
			return (Criteria) this;
		}

		public Criteria andRemark5NotEqualTo(String value)
		{
			addCriterion("remark5 <>", value, "remark5");
			return (Criteria) this;
		}

		public Criteria andRemark5GreaterThan(String value)
		{
			addCriterion("remark5 >", value, "remark5");
			return (Criteria) this;
		}

		public Criteria andRemark5GreaterThanOrEqualTo(String value)
		{
			addCriterion("remark5 >=", value, "remark5");
			return (Criteria) this;
		}

		public Criteria andRemark5LessThan(String value)
		{
			addCriterion("remark5 <", value, "remark5");
			return (Criteria) this;
		}

		public Criteria andRemark5LessThanOrEqualTo(String value)
		{
			addCriterion("remark5 <=", value, "remark5");
			return (Criteria) this;
		}

		public Criteria andRemark5Like(String value)
		{
			addCriterion("remark5 like", value, "remark5");
			return (Criteria) this;
		}

		public Criteria andRemark5NotLike(String value)
		{
			addCriterion("remark5 not like", value, "remark5");
			return (Criteria) this;
		}

		public Criteria andRemark5In(List<String> values)
		{
			addCriterion("remark5 in", values, "remark5");
			return (Criteria) this;
		}

		public Criteria andRemark5NotIn(List<String> values)
		{
			addCriterion("remark5 not in", values, "remark5");
			return (Criteria) this;
		}

		public Criteria andRemark5Between(String value1, String value2)
		{
			addCriterion("remark5 between", value1, value2, "remark5");
			return (Criteria) this;
		}

		public Criteria andRemark5NotBetween(String value1, String value2)
		{
			addCriterion("remark5 not between", value1, value2, "remark5");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	public static class Criterion
	{
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition()
		{
			return condition;
		}

		public Object getValue()
		{
			return value;
		}

		public Object getSecondValue()
		{
			return secondValue;
		}

		public boolean isNoValue()
		{
			return noValue;
		}

		public boolean isSingleValue()
		{
			return singleValue;
		}

		public boolean isBetweenValue()
		{
			return betweenValue;
		}

		public boolean isListValue()
		{
			return listValue;
		}

		public String getTypeHandler()
		{
			return typeHandler;
		}

		protected Criterion(String condition)
		{
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler)
		{
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>)
			{
				this.listValue = true;
			} else
			{
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value)
		{
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler)
		{
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue)
		{
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table diamondsinfo
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 04 15:27:11 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}