package ats.blockchain.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import ats.blockchain.web.model.Basketinfo;
import ats.blockchain.web.model.BasketinfoExample;

public interface BasketinfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	long countByExample(BasketinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	int deleteByExample(BasketinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	int deleteByPrimaryKey(String basketno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	int insert(Basketinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	int insertSelective(Basketinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	List<Basketinfo> selectByExample(BasketinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	Basketinfo selectByPrimaryKey(String basketno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Basketinfo record, @Param("example") BasketinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	int updateByExample(@Param("record") Basketinfo record, @Param("example") BasketinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	int updateByPrimaryKeySelective(Basketinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basketinfo
	 * @mbg.generated  Sat Sep 08 10:59:14 CST 2018
	 */
	int updateByPrimaryKey(Basketinfo record);
}