package ats.blockchain.web.dao;

import ats.blockchain.web.model.Diamondsinfo;
import ats.blockchain.web.model.DiamondsinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiamondsinfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	long countByExample(DiamondsinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	int deleteByExample(DiamondsinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	int deleteByPrimaryKey(Integer tradeid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	int insert(Diamondsinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	int insertSelective(Diamondsinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	List<Diamondsinfo> selectByExample(DiamondsinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	Diamondsinfo selectByPrimaryKey(Integer tradeid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Diamondsinfo record, @Param("example") DiamondsinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	int updateByExample(@Param("record") Diamondsinfo record, @Param("example") DiamondsinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	int updateByPrimaryKeySelective(Diamondsinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diamondsinfo
	 * @mbg.generated  Sat Sep 08 10:58:45 CST 2018
	 */
	int updateByPrimaryKey(Diamondsinfo record);
}